import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {StudyEngine} from '../server/engine.mjs';
import {WorkspaceStore} from '../server/store.mjs';
import {modelSafeResult} from '../server/model-result.mjs';
const alice={id:'integration-alice',scopes:['notable.read','notable.write']};
const readOnly={...alice,scopes:['notable.read']};
test('engine integrates course organization, reviewed continuity and conflict-safe notes',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'nooks-context-')); t.after(()=>rm(dir,{recursive:true,force:true}));
 const engine=new StudyEngine(new WorkspaceStore(dir,{seeded:false}));
 const {course}=await engine.call('course_save',{course:{title:'Biology'}},alice);
 const {topic}=await engine.call('topic_save',{topic:{title:'Cells',courseId:course.id}},alice);
 const {artifact:note}=await engine.call('artifact_save',{artifact:{kind:'note',title:'Cell notes',subject:'Biology',content:'Human notes',topicId:topic.id}},alice);
 assert.equal(note.revision,1); assert.equal(note.courseId,course.id);
 const {proposal}=await engine.call('note_revision_propose',{artifactId:note.id,expectedRevision:1,content:'Reviewed draft'},alice);
 assert.equal((await engine.call('artifact_get',{artifactId:note.id},readOnly)).artifact.content,'Human notes');
 await engine.call('note_update',{artifactId:note.id,expectedRevision:1,content:'My intervening edit'},alice);
 await assert.rejects(()=>engine.call('note_revision_apply',{proposalId:proposal.id,expectedRevision:2,confirmed:true},alice),/changed|stale|revision/i);
 await assert.rejects(()=>engine.call('artifact_save',{artifact:{...note,content:'Stale overwrite'}},alice),/changed|revision/i);
 await assert.rejects(()=>engine.call('course_save',{course:{title:'Blocked'}},readOnly),/permission/i);
 const {session}=await engine.call('session_save',{confirmed:true,session:{title:'Next session',summary:'Review cell membranes.',topicId:topic.id,artifactIds:[note.id],nextSteps:['Practice transport']}},alice);
 const context=await engine.call('context_get',{sessionId:session.id,maxChars:2000},readOnly);
 assert.equal(context.context.session.summary,'Review cell membranes.'); assert.equal(context.workspace,undefined);
 const reloaded=new StudyEngine(new WorkspaceStore(dir,{seeded:false}));
 assert.equal((await reloaded.call('artifact_get',{artifactId:note.id},alice)).artifact.content,'My intervening edit');
 await assert.rejects(()=>reloaded.call('artifact_get',{artifactId:note.id},{id:'bob',scopes:['notable.read']}),/found/i);
 await engine.call('artifact_delete',{artifactId:note.id},alice);
 const {workspace}=await engine.call('workspace_get',{},alice);
 assert.equal(workspace.organization.noteProposals.length,0);assert.deepEqual(workspace.organization.sessions[0].artifactIds,[]);
});
test('model envelope never attaches full libraries, revisions, summaries or image pixels',()=>{
 const workspace={space:{name:'Private',backgroundImage:'data:image/png;base64,secret'},artifacts:[{id:'n',title:'Private title',content:'secret body'}],organization:{courses:[{id:'c',title:'Course',revision:1}],topics:[],sessions:[{summary:'private summary'}],noteRevisions:[{content:'private version'}]},stats:{xp:0}};
 const result=modelSafeResult({structuredContent:{workspace,artifact:{id:'selected',content:'chosen material'}},content:[{type:'text',text:'Saved.'}]});
 const visible=JSON.stringify(result.structuredContent);
 for(const value of ['secret body','Private title','private summary','private version','base64,secret']) assert.equal(visible.includes(value),false);
 assert.ok(visible.includes('chosen material')); assert.equal(result._meta.notableData.workspace,workspace);
 assert.equal(workspace.artifacts[0].content,'secret body');
});
