/** Local-only resource-boundary audit. Every upstream response is injected; no credentials/network. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable,PassThrough} from 'node:stream';
import {setTimeout as wait} from 'node:timers/promises';
import {createBrowserApiHandler} from '../../web/server/browser-api.mjs';
import {validateArtifact} from '../../web/server/engine.mjs';
import {generateStudyMaterial} from '../../web/server/study-generation.mjs';
const ID='00000000-0000-4000-8000-000000000001',MAX=2*1024*1024;
const env={SUPABASE_URL:'https://audit.invalid',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_fake_audit',SUPABASE_SERVICE_KEY:'sb_secret_fake_audit',NOOKS_PUBLIC_URL:'https://app.invalid'};
function backend(custom){const calls=[];const fetchImpl=async(url,options)=>{calls.push({path:new URL(url).pathname,signal:options.signal});if(custom)return custom(url,options);if(url.endsWith('/auth/v1/user'))return Response.json({id:ID});if(url.endsWith('nooks_resolve_identity'))return Response.json({id:ID});if(url.endsWith('nooks_request_limit'))return Response.json({allowed:true});assert.fail('Unexpected upstream read/write');};return{calls,handler:createBrowserApiHandler({env,fetchImpl,logger:()=>{}})};}
function request(chunks=[],headers={},preparsed){const req=chunks instanceof Readable?chunks:Readable.from(chunks);Object.assign(req,{url:'/api/tools/profile_update',method:'POST',headers:{origin:'https://app.invalid',authorization:'Bearer fake-user-token','content-type':'application/json',...headers}});if(preparsed!==undefined)req.body=preparsed;return req;}
async function invoke(handler,req){let status,body;await handler(req,{writeHead:s=>{status=s},end:data=>{body=JSON.parse(data)}});return{status,body};}
const expectedUpstream=['/auth/v1/user','/rest/v1/rpc/nooks_resolve_identity','/rest/v1/rpc/nooks_request_limit'];
test('advertised oversized input returns413 but performs three upstream operations first',async()=>{const b=backend();let consumed=false;const req=request(Readable.from((async function*(){consumed=true;yield Buffer.from('{}');})()),{'content-length':String(MAX+1)});const r=await invoke(b.handler,req);assert.equal(r.status,413);assert.equal(r.body.error.code,'TOO_LARGE');assert.equal(consumed,false);assert.deepEqual(b.calls.map(c=>c.path),expectedUpstream);});
test('malformed JSON and wrong media type still consume Auth, identity and quota operations',async()=>{for(const req of [request([Buffer.from('{')]),request([Buffer.from('{}')],{'content-type':'text/plain'})]){const b=backend(),r=await invoke(b.handler,req);assert.equal(r.status,400);assert.deepEqual(b.calls.map(c=>c.path),expectedUpstream);}});
test('actual streamed bytes over2MiB are rejected without Content-Length',async()=>{const b=backend(),r=await invoke(b.handler,request([Buffer.alloc(MAX,32),Buffer.from('x')]));assert.equal(r.status,413);assert.equal(r.body.error.code,'TOO_LARGE');});
test('preparsed and multibyte bodies are bounded by serialized UTF8 bytes',async()=>{for(const req of [request([],{}, {displayName:'x'.repeat(MAX),avatar:0}),request([Buffer.from(JSON.stringify({displayName:'界'.repeat(700000),avatar:0}))])]){const b=backend(),r=await invoke(b.handler,req);assert.equal(r.status,413);}});
test('open input stream remains pending until caller ends it; no application body deadline is attached',async()=>{const b=backend(),stream=new PassThrough(),req=request(stream);let settled=false;const promise=invoke(b.handler,req).finally(()=>{settled=true});stream.write('{');await wait(250);assert.equal(settled,false);assert.deepEqual(b.calls.map(c=>c.path),expectedUpstream);stream.end('}');const r=await promise;assert.equal(r.status,400);});
test('request destruction does not abort an in-flight upstream Auth signal',async()=>{let release,started;const gate=new Promise(resolve=>{release=resolve}),ready=new Promise(resolve=>{started=resolve});const b=backend(async()=>{started();await gate;return Response.json({},{status:401});});const req=request([Buffer.from('{}')]);req.on('error',()=>{});const pending=invoke(b.handler,req);await ready;req.destroy(new Error('Simulated local client disconnect'));await wait(20);assert.equal(b.calls.length,1);assert.ok(b.calls[0].signal);assert.equal(b.calls[0].signal.aborted,false);release();assert.equal((await pending).status,401);});
test('large artifact arrays and nested choices reject before item traversal beyond product limits',()=>{const base={title:'Audit',kind:'flashcards'};assert.throws(()=>validateArtifact({...base,cards:Array(201).fill({})}),/1–200/);assert.throws(()=>validateArtifact({title:'Audit',kind:'quiz',questions:Array(101).fill({})}),/1–100/);assert.throws(()=>validateArtifact({title:'Audit',kind:'quiz',questions:[{prompt:'Q',options:Array(9).fill('x'),correctIndex:0}]}),/2–8/);assert.throws(()=>validateArtifact({title:'Audit',kind:'quiz',questions:[{prompt:'Q',acceptedAnswers:Array(21).fill('x')}]}),/1–20/);});
test('oversized generation selection rejects before store or provider work',async()=>{let calls=0;await assert.rejects(generateStudyMaterial({args:{kind:'note',requestId:'00000000-0000-4000-8000-000000000001',materialIds:Array(9).fill('id')},store:{read(){calls++;assert.fail('No store read expected')}},fetchImpl(){calls++;assert.fail('No provider request expected')}}),/eight saved materials/);assert.equal(calls,0);});
test('bounded deeply nested JSON returns400 for both byte and host-preparsed bodies',async()=>{const raw='{"displayName":'+ '['.repeat(10000)+'0'+']'.repeat(10000)+',"avatar":0}';assert.ok(Buffer.byteLength(raw)<21000);const streamed=backend(),parsed=backend();assert.equal((await invoke(streamed.handler,request([Buffer.from(raw)]))).status,400);const r=await invoke(parsed.handler,request([],{},JSON.parse(raw)));assert.equal(r.status,400);assert.equal(r.body.error.code,'INVALID_INPUT');});
