import { listOrganizationTools } from './organization-tools.mjs';
import { spaceEnums } from './space.mjs';
import { PROGRESS_ROOM_IDS } from './room-progress.mjs';
import { WORKSPACE_SESSION_VIEWS } from './workspace-session.mjs';
import { WORKSPACE_WIDGET_IDS } from './workspace-layout.mjs';
export const UI_URI = 'ui://notable/workspace-v2.html';
export const LEGACY_UI_URI = 'ui://notable/workspace-v1.html';
export const UI_MIME = 'text/html;profile=mcp-app';
export const WORKSPACE_VIEWS = WORKSPACE_SESSION_VIEWS;
// Native sidebar icons inherit the host's current theme instead of a brand fill.
export const UI_ICON = 'data:image/svg+xml;base64,' + Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.33" stroke-linecap="round" stroke-linejoin="round"><path d="M3 4.5c3-1 5-1 7 .5 2-1.5 4-1.5 7-.5v11c-3-1-5-1-7 .5-2-1.5-4-1.5-7-.5zM10 5v11"/></svg>').toString('base64');
const string = { type: 'string' };
const artifactSchema = {
  type: 'object', required: ['kind', 'title', 'subject'], additionalProperties: false,
  properties: {
    id: string, kind: { type: 'string', enum: ['note', 'quiz', 'exam', 'flashcards'] }, title: string, subject: string,
    revision: { type: 'integer', minimum: 1 }, expectedRevision: { type: 'integer', minimum: 1 }, courseId: { anyOf: [string, {type:'null'}] }, topicId: { anyOf: [string, {type:'null'}] }, color: string, description: string, source: string, favorite: { type: 'boolean' }, createdAt: string, updatedAt: string,
    content: { type: 'string', description: 'Markdown text for a note. Required for kind=note.' },
    cards: { type: 'array', minItems: 1, maxItems: 200, items: { type: 'object', required: ['front', 'back'], properties: { id: string, front: string, back: string, hint: string }, additionalProperties: false } },
    questions: { type: 'array', minItems: 1, maxItems: 100, items: { type: 'object', required: ['prompt'], properties: { id: string, prompt: string, options: { type: 'array', items: string, minItems: 2, maxItems: 8 }, correctIndex: { type: 'integer', minimum: 0 }, answer: string, acceptedAnswers: { type: 'array', items: string }, explanation: string }, additionalProperties: false } },
  },
};
const schema = (properties = {}, required = []) => ({ type: 'object', properties, required, additionalProperties: false });
const descriptors = [
  ['workspace_layout_update', 'Save widget arrangement', 'Save one widget position in the connected account. Coordinates are normalized from 0 to 1 over its available movement range. Use position: null to restore one widget’s default placement, or reset: true alone to restore the whole arrangement. Unrelated widget positions are preserved.', { ...schema({ id: { type: 'string', enum: WORKSPACE_WIDGET_IDS }, position: { anyOf: [schema({ x: { type: 'number', minimum: 0, maximum: 1 }, y: { type: 'number', minimum: 0, maximum: 1 } }, ['x', 'y']), { type: 'null' }] }, reset: { type: 'boolean', const: true } }), oneOf: [{ required: ['id', 'position'], not: { required: ['reset'] } }, { required: ['reset'], not: { anyOf: [{ required: ['id'] }, { required: ['position'] }] } }] }, false],
  ['workspace_session_open', 'Connect this Nooks tab', 'Register or renew this app instance using the UUID created by this Nooks tab. Returns its current navigation sequence and expiry without replaying an old command. Renew explicitly about every five minutes while the tab is active. Never select another or most-recent session.', schema({ sessionId: { type: 'string', format: 'uuid' } }, ['sessionId']), false],
  ['workspace_session_poll', 'Read this tab’s navigation', 'Read the latest pending navigation for this connected app instance after its current sequence. Read-only: does not extend session lifetime. Returns only target IDs or a view, never saved study content or a library. Reconnect an expired session.', schema({ sessionId: { type: 'string', format: 'uuid' }, afterSequence: { type: 'integer', minimum: 0, maximum: Number.MAX_SAFE_INTEGER } }, ['sessionId', 'afterSequence']), true],
  ['workspace_navigate', 'Navigate the open Nooks tab', 'Queue navigation in the already-open Nooks app identified by the exact sessionId supplied by that app context. Never guess or reuse a different session. Choose one saved artifactId or view. alongsideArtifactId is allowed only for a quiz, exam or flashcard set with a saved note as reference. A successful reply confirms queued navigation, not that the student viewed it. This tool does not open another app instance.', { ...schema({ sessionId: { type: 'string', format: 'uuid' }, artifactId: { type: 'string', minLength: 1, maxLength: 128 }, view: { type: 'string', enum: WORKSPACE_VIEWS }, alongsideArtifactId: { type: 'string', minLength: 1, maxLength: 128 } }, ['sessionId']), oneOf: [{ required: ['artifactId'], not: { required: ['view'] } }, { required: ['view'], not: { anyOf: [{ required: ['artifactId'] }, { required: ['alongsideArtifactId'] }] } }] }, false],
  ['workspace_get', 'Get study space', 'Load the study UI and a compact library overview. Full private material is delivered only to the widget. Use library_search, artifact_get and context_get for user-selected study content. Anonymous calls return sample material.', schema(), true],
  ['workspace_render', 'Open Nooks study space', 'Open a Nooks study app instance when no active app session is available. For an open app prefer its nooks_present tool, otherwise use workspace_navigate with the current app context workspaceSessionId as sessionId to update that same tab. Never guess the destination or repeatedly open more instances. Pass artifactId to open an existing saved item owned by the connected student, including the id returned by artifact_save. Or pass a complete artifact generated by ChatGPT for an unsaved preview, including without an account. Pass view to navigate directly to study, library, explore, focus, plan, collection, music or people. Choose only one of artifactId, artifact or view. Omit all three to load the workspace without changing its current view. Generate educational content from user-selected sources in the conversation; do not send the student to another creation form.', { ...schema({ artifactId: { type: 'string', minLength: 1, maxLength: 128, description: 'ID of an existing study item in the connected account. Use the id confirmed by artifact_save or library_search.' }, artifact: artifactSchema, view: { type: 'string', enum: WORKSPACE_VIEWS, description: 'Open this interface directly. Use study for the welcome study nook. This does not change, join, publish or start anything.' } }), allOf: [{ not: { required: ['artifact', 'artifactId'] } }, { not: { required: ['view', 'artifact'] } }, { not: { required: ['view', 'artifactId'] } }] }, true, true],
  ['artifact_save', 'Save study material', 'Save a complete note, quiz, exam or flashcard set in the connected student’s private Nooks library. An explicit request to create Nooks material defaults to a new saved artifact; ChatGPT prepares the educational content and omits id/revision for new work. After a successful save, use the mounted app’s nooks_present tool with the returned artifact.id; otherwise use workspace_navigate with the active workspaceSessionId from app context as sessionId to show it in the existing tab. Use workspace_render with artifactId only when no active app session is available. Supply an existing id only for a requested update, with its loaded revision; stale note edits cannot overwrite newer work. For AI-suggested note changes use note_revision_propose so the student can review first. Saving does not invoke a separately billed model.', schema({ artifact: artifactSchema }, ['artifact']), false],
  ['artifact_delete', 'Delete study material', 'Delete one item from the connected student’s library. Ask the student to confirm deletion first.', schema({ artifactId: string }, ['artifactId']), false, false, true],
  ['practice_checkpoint_get', 'Resume study practice', 'Load the signed-in student’s unfinished practice position for one owned material and its current revision. This never awards progress.', schema({artifactId:string},['artifactId']), true],
  ['practice_checkpoint_save', 'Keep your practice place', 'Save bounded, validated card or quiz UI state for one owned study item. No score, focus time or rewards are awarded. A null checkpoint clears the position.', schema({artifactId:string,checkpoint:{anyOf:[{type:'object'},{type:'null'}]}},['artifactId','checkpoint']), false],
  ['progress_record', 'Record study practice', 'Record raw question answers, flashcard confidence ratings, or matching-game evidence with artifactRevision from the version actually studied. Server computes score and XP; client score/xp are ignored. Never replace a stale or missing revision with the current one: keep the original result and begin a new practice session. Retry with the same sessionId to avoid duplicate awards; already committed sessions return their original result unchanged. Legacy clients without a revision need an exact compatible server-saved checkpoint for that session; the server never guesses. Matching, flashcard and quiz rewards are capped to one award per artifact and mode per UTC day.', schema({ artifactId: string, artifactRevision: { type: 'integer', minimum: 1, description: 'Revision of the complete material used in this practice session. Capture it before studying; never fetch a new revision to retry old answers. New clients must supply it; omission is accepted only with an exact compatible server-saved checkpoint for this session.' }, sessionId: string, roomId: { type: 'string', enum: PROGRESS_ROOM_IDS, description: 'Nook captured when practice began; custom for uploaded artwork.' }, kind: { type: 'string', enum: ['quiz', 'exam', 'flashcards', 'sprint', 'match'] }, answers: { type: 'object', additionalProperties: { anyOf: [{ type: 'string' }, { type: 'integer' }] } }, cardRatings: { type: 'object', additionalProperties: { type: 'string', enum: ['again', 'hard', 'good', 'easy'] } }, matches: { type: 'array', items: { type: 'object', properties: { cardId: string, front: string, back: string }, required: ['cardId', 'front', 'back'], additionalProperties: false } }, durationSeconds: { type: 'integer', minimum: 0 }, score: { type: 'integer' }, total: { type: 'integer' }, xp: { type: 'integer' } }, ['artifactId', 'sessionId']), false],
  ['room_reward_place', 'Place an unlocked nook reward', 'Equip or remove one reward in its own study nook. Unlocks are based on real credited active focus time, never client-supplied progress. Each nook can display up to three unlocked rewards. Retries are safe.', schema({ roomId: { type: 'string', enum: PROGRESS_ROOM_IDS }, rewardId: string, placed: { type: 'boolean' } }, ['roomId', 'rewardId', 'placed']), false],
  ['focus_start', 'Start a focus session', 'Start or resume the student’s active focus session. The server tracks elapsed time for honest focus points.', schema({ minutes: { type: 'integer', minimum: 1, maximum: 180 }, subject: string, artifactId: { type: 'string', description: 'Optional saved study material in this account. Links the focus session to its current revision.' }, nookId: { type: 'string', format: 'uuid', description: 'Optional joined community nook. The server checks membership and binds this focus session to it.' } }), false],
  ['focus_update', 'Pause or resume focus', 'Pause, resume, or cancel an active focus session. Paused time never earns points.', schema({ sessionId: string, action: { type: 'string', enum: ['pause', 'resume', 'cancel'] } }, ['sessionId', 'action']), false],
  ['focus_complete', 'Finish a focus session', 'Finish a server-issued focus session. Points are awarded only after the planned active minutes have elapsed. Retries cannot double award points.', schema({ sessionId: string }, ['sessionId']), false],
  ['plan_get', 'Read your study plan', 'Read the connected student’s current tasks, including their IDs and completion state, plus workspaceRevision. Before adding, updating or completing a task through plan_save, read this plan, preserve every unrelated task, and pass workspaceRevision as expectedRevision. This returns only the plan, not notes or conversation history.', schema(), true],
  ['study_status_get', 'Read your current study status', 'Read the connected student’s current nook appearance identifier, active focus session ID and timer state, and this nook’s earned progress and reward IDs. Use this before pausing or resuming focus, placing an earned reward, or answering progress questions. Elapsed focus time is not proof of attention. Does not return notes, other nooks, full focus history, or automatically join a community.', schema(), true],
  ['plan_save', 'Save a study plan', 'Replace the connected student’s study tasks with a complete plan. For an additive change or marking a task done, call plan_get first, preserve every unrelated task and its ID, and pass its workspaceRevision as expectedRevision. On a revision conflict reread and merge the requested change into the new plan; never retry the stale replacement or replace the plan with just the changed task. Mark tasks complete with done=true. Plan from the student’s actual exam dates and available time, then show view=plan through workspace_navigate with the active app sessionId; use workspace_render only when no active app session is available.', schema({ expectedRevision: { type: 'integer', minimum: 0, description: 'workspaceRevision returned by plan_get. Prevents overwriting concurrent changes.' }, plan: { type: 'object', required: ['tasks'], properties: { tasks: { type: 'array', maxItems: 100, items: { type: 'object', required: ['title'], properties: { id: string, title: string, subject: string, done: { type: 'boolean' }, dueDate: { type: 'string', description: 'YYYY-MM-DD date.' } }, additionalProperties: false } } }, additionalProperties: false } }, ['plan', 'expectedRevision']), false],
  ['space_customize', 'Decorate your study nook', 'Update only the supplied settings of the connected student’s study nook; omitted appearance settings and custom artwork are preserved. Choosing a catalog room without backgroundImage replaces custom artwork with that scene. Pass backgroundImage as empty text to remove it explicitly. This does not publish it. New images must be user-selected PNG, JPEG or WebP data URLs under1MB.', schema({ space: { type: 'object', properties: { name: string, tagline: string, theme: { type: 'string', enum: spaceEnums.theme }, room: { type: 'string', enum: spaceEnums.room }, accent: { type: 'string', enum: ['#8bc8a7', '#e9ab86', '#b1a0d8', '#8cbad1', '#d7a0b1'] }, companion: { type: 'string', enum: spaceEnums.companion }, layout: { type: 'string', enum: ['calm', 'focused'] }, decorations: { type: 'array', items: { type: 'string', enum: ['sparkles', 'stickers'] }, maxItems: 2 }, backgroundImage: string }, additionalProperties: false } }, ['space']), false],
  ['space_share', 'Share your study nook appearance', 'Create a read-only public snapshot ONLY after the student explicitly chooses to share. Shares include nook appearance, any selected background image, and an optional description. Never include notes, quizzes, flashcards, artifact titles or identity. Include aggregate progress only if the student explicitly opts in.', schema({ description: string, includeProgress: { type: 'boolean', default: false } }), false],
  ['space_share_get', 'Read a shared nook appearance', 'Read one explicitly shared appearance snapshot by its share ID. Never includes private study materials.', schema({shareId:string}, ['shareId']), true],
  ['space_unshare', 'Revoke a shared nook', 'Revoke an appearance share belonging to the connected student so its link no longer works.', schema({ shareId: string }, ['shareId']), false, false, true],
];

export const toolNames = new Set([...descriptors.map(([name]) => name), ...listOrganizationTools().map(tool => tool.name)]);
export function listTools({ demo = false, oauthConfigured = false } = {}) {
  return [...descriptors.map(([name, title, description, inputSchema, readOnly, render, destructive]) => {
    const securitySchemes = demo || !oauthConfigured ? [{ type: 'noauth' }] : readOnly ? [{ type: 'noauth' }, { type: 'oauth2', scopes: ['notable.read'] }] : [{ type: 'oauth2', scopes: ['notable.read', 'notable.write'] }];
    return {
      name, title, description, inputSchema, ...(render ? { icons: [{ src: UI_ICON, mimeType: 'image/svg+xml' }] } : {}),
      annotations: { readOnlyHint: !!readOnly, destructiveHint: !!destructive || ['artifact_save', 'plan_save', 'space_customize'].includes(name), idempotentHint: !['focus_start', 'artifact_save', 'space_share', 'workspace_navigate'].includes(name), openWorldHint: name === 'space_share' },
      securitySchemes,
      _meta: { securitySchemes, ...(['workspace_session_open', 'workspace_session_poll', 'workspace_layout_update'].includes(name) ? { ui: { visibility: ['app'] } } : {}), ...(render ? { ui: { resourceUri: UI_URI }, 'openai/ui': { entrypoints: [{ type: 'global' }, { type: 'thread' }] }, 'openai/outputTemplate': UI_URI } : {}), 'openai/widgetAccessible': true },
    };
  }), ...listOrganizationTools({demo,oauthConfigured})];
}
