"""Art-directed regions; coordinates measured on 600 x 338 artwork contact sheets.
Every subject below was checked against its actual final artwork, not its title.
"""
BASE = ('Animate this exact reference into a calm living study background. Absolutely locked tripod camera, zero pan, zoom, tilt, parallax, cuts or framing drift. Preserve the exact original art style, geometry, composition, colors, furniture and object identities. Real-world gentle physics, very small localized motion at normal speed; never a slow-motion effect. No added subjects, people, animals, text, sparks, floating particles or magical effects. Everything not specifically named is perfectly still. No light switching, strobing, exposure breathing, morphing or dramatic wind. Return to the identical starting composition for a seamless loop. Silent video. ')
# region: kind, geometry, alpha (0-255), label. Feathered during finishing.
def e(box,alpha,label):return {'kind':'ellipse','points':box,'alpha':alpha,'label':label}
def light(box,alpha,label):return {**e(box,alpha,label),'mode':'light-only'}
def p(points,alpha,label):return {'kind':'polygon','points':points,'alpha':alpha,'label':label}
def r(box,alpha,label):
 x,y,X,Y=box;return p([(x,y),(X,y),(X,Y),(x,Y)],alpha,label)
SPECS={
'rainy-library':('Only a faint transparent wisp of real cup steam moves above the blue floral cup. Preserve the original rainy skyline, window frames, architecture, lamps and desk perfectly still.',[e((46,226,69,250),60,'cup steam above rim; original skyline fixed')]),
'howls-moving-study':('A delicate transparent steam wisp rises above the floral foreground cup. The original stove flame varies only in bounded AI-derived luminance, preserving every iron bar and the original flame geometry. Keep the sleeping cat, lantern, landscape and furnishings perfectly still.',[e((155,235,179,265),55,'cup steam above rim'),light((296,156,316,176),220,'stove warmth with original iron bars fixed')]),
'gryffindor-common-room':('Animate only the upper open hearth flames, above and clear of the rigid fire screen. Preserve both ornamental posts, every screen bar, the original wall candles, sleeping cat and entire room perfectly still.',[p([(112,139),(146,136),(151,159),(145,167),(112,167)],170,'upper open hearth flames above fixed screen')]),
'neon-tokyo':('Only fine rain trails slide down the exterior window glass. Faint transparent steam curls just above the dark mug at the front right. Neon signs remain constant, skyline and all window frames stay still.',[e((394,243,414,269),28,'mug steam')]),
'alpine-cabin':('Only the existing hearth fire flickers gently inside the left fireplace. One fine transparent steam wisp rises above the tree-pattern mug at the front left. Snowy landscape stays still.',[p([(58,149),(95,133),(127,149),(130,206),(62,219)],215,'fire opening'),e((101,231,122,264),35,'mug steam')]),
'totoro-forest-window':('Very fine rain falls in the garden beyond the window, with a tiny natural tremble in a few leaves near the opening. Barely visible steam rises above the blue floral cup near the desk center. The sleeping cat stays exactly curled and completely still.',[p([(109,54),(190,47),(189,177),(106,206)],130,'rain left garden'),r((395,67,515,174),120,'rain right garden'),e((319,217,346,258),55,'cup steam')]),
'slytherin-common-room':('Very subtle underwater light patterns undulate within the tall green lake windows, without swimming creatures or moving architecture. Existing fire at lower left flickers softly inside its opening. Foreground candles have tiny steady flame motion.',[p([(746-600,71),(770-600,38),(793-600,75),(791-600,169),(748-600,143)],100,'first lake pane'),p([(850-600,57),(874-600,28),(898-600,62),(896-600,184),(853-600,161)],100,'second lake pane'),e((48,172,79,201),210,'hearth'),e((557,230,575,259),155,'foreground candle'),e((254,49,292,89),0,'preserve shark silhouette')]),
'kikis-bakery-attic':('A fine transparent wisp of warm tea steam rises above the floral mug at the front right. The plant leaves along the upper right window edge barely stir. The sleeping black cat remains perfectly still; rooftops and boats do not move.',[e((461,186,489,240),55,'tea steam'),e((462,10,493,87),90,'window vine')]),
'midnight-train':('Rain droplets slowly trace down the outside of the broad compartment window. Faint tea steam rises from the patterned cup beside the lamp. Keep the landscape stationary: no train-camera shaking, rushing scenery or rolling horizon.',[e((141,216,156,237),40,'tea steam')]),
'hufflepuff-common-room':('The existing fire at the far right flickers softly inside the hearth. Faint transparent steam lifts just above the yellow cup in the foreground. The room, hanging plants and sunlit windows remain completely still.',[p([(550,158),(580,150),(598,167),(598,202),(551,213)],210,'right hearth'),e((414,231,440,278),55,'cup steam')]),
'ravenclaw-tower':('Tiny steady flickers animate the existing candle flames on the right writing table. A very fine transparent wisp rises above the blue foreground mug. No moving stars, clouds or light rays; telescope and furnishings remain fixed.',[e((541,197,549,217),170,'table candle'),e((565,183,576,209),160,'tall candle'),e((468,227,497,272),55,'mug steam')]),
'stardew-farmhouse':('Animate only the small orange fire inside the black wood stove and a tiny warm flame inside the foreground lantern. A fine steam wisp rises above the foreground cream mug. Preserve the original pixel-textured painting and blocky details. The sleeping orange cat stays still.',[e((189,507-360,215,534-360),220,'stove flame'),e((550,628-360,579,666-360),155,'lantern flame'),e((133,584-360,159,638-360),55,'cup steam')]),
'spirited-bathhouse':('Thin existing bathhouse mist drifts slowly and naturally over the courtyard below the bridge. The narrow waterfall at the far left flows continuously downward within its existing channel. No characters, lantern swings or shifting buildings.',[p([(91,93),(116,110),(130,163),(129,210),(106,204),(98,155)],160,'left waterfall'),p([(147,183),(211,170),(263,187),(259,211),(148,211)],90,'courtyard mist')]),
'bookshop-cat':('The striped cat asleep on the front counter has only a tiny slow breathing movement, no head turn or change of pose. The small fire in the back-right stove flickers quietly within its opening. Thin transparent steam curls above the cup beside the left desk lamp.',[e((105,203,202,251),140,'sleeping cat torso'),e((401,134,428,166),220,'stove flame')]),
'sunlit-greenhouse':('Tiny rain trails descend outside the central conservatory glass. Only a few delicate fern tips barely sway. Fine transparent steam rises above the foreground botanical mug. Keep all structural glass bars and pots still.',[r((280,58,307,142),135,'center glass'),r((331,65,365,132),130,'right glass'),e((52,242,82,290),50,'mug steam'),e((176,93,215,151),80,'fern tips')]),
'dragon-hatchery':('Tiny natural flame motion in the large foreground lantern at the far right. The glowing warm nest in the stone alcove only has a barely perceptible local glow fluctuation, never hatching or moving an egg. Faint transparent steam above the dark front-left cup.',[e((558,222,584,286),175,'lantern flame'),e((490,121,545,159),45,'nest warmth'),e((120,211,140,259),50,'cup steam')]),
'velaris-study':('Very small soft ripples animate only the distant river surface below the city. Keep reflections gently shimmering in place, no traveling boats or stars. The existing foreground candle flame softly flickers.',[p([(270,151),(463,150),(507,173),(428,190),(316,186)],115,'river ripples')]),
'dragon-rider-study':('Only the fire inside the right stone hearth flickers at low intensity. Very slight candle flame flutter along the mantel. Keep all dragons, skies and distant architecture absolutely motionless; do not add or animate flying creatures.',[p([(550,152),(573,138),(599,142),(599,203),(550,196)],205,'hearth fire'),e((491,73,513,86),150,'mantel candles')]),
'hobbit-study':('A tiny natural movement stirs just the leaf tips directly outside the round doorway, without branches swaying. A delicate transparent wisp of tea steam rises above the green foreground mug. The countryside, furniture, food and room stay still.',[e((126,230,151,282),60,'green mug steam'),e((188,29,233,55),85,'doorway leaf tips')]),
'animal-crossing-island':('Gentle small ocean ripples shimmer outside the left window and through the open arched door. A tiny transparent steam wisp rises above the green-patterned foreground cup. Preserve the miniature toy-like art and keep all furnishings perfectly still.',[r((59,117,72,135),110,'open left sea excluding pier and cliff'),r((343,110.5,358,113.5),110,'open doorway sea above railing'),e((104,206,130,251),50,'cup steam')]),
'cinnamoroll-cloud-cafe':('A delicate short transparent steam curl rises above the latte in the foreground. The distant soft clouds barely change contour in the large central opening. Keep the plush characters, cloud seats, pastries and all furniture completely still.',[e((160,214,190,260),55,'latte steam'),e((218,106,333,142),60,'distant clouds')]),
'witch-apothecary':('The already visible thin incense or kettle vapor at the far right curls gently upward, staying exactly near its source. Both existing candle flames remain perfectly still. No magical particles, potion bubbling, moving herbs or changing moon.',[e((550,92,589,173),110,'existing vapor')]),
'kyoto-teahouse':('Fine rain falls only in the open garden beyond the veranda. Tiny ripples spread across the small garden water surface. A fine transparent steam wisp rises above the tea cup on the right. Shoji doors, hanging ornament and indoor objects stay fixed.',[p([(102,59),(178,44),(200,163),(135,182)],110,'garden rain'),e((233,169,291,194),140,'garden stream'),e((427,218,454,262),50,'tea steam')]),
'oxford-library':('Animate only the existing low fire inside the far-right fireplace. Preserve the foreground candle and its single original flame completely still. All pages, walls, windows, cups and room lighting remain steady.',[e((563,172,595,207),210,'right fire')]),
'capybara-onsen':('Warm thin steam drifts very slowly just above the hot pool. Small ripples move gently on the water around the two completely still resting capybaras. The narrow waterfall on the far right pours calmly downward. Preserve animal bodies, faces, citrus, stone and architecture exactly.',[p([(198,199),(266,192),(300,211),(388,205),(400,224),(496,232),(479,247),(295,237)],115,'pool surface avoiding animals'),e((283,145,333,195),85,'pool vapor'),p([(490,155),(508,144),(505,177),(484,198),(473,193)],170,'waterfall')]),
'pokemon-research-cottage':('The small existing stove fire at the far left flickers warmly. Faint transparent steam rises above the nearby cream mug. Keep sleeping creatures, terrariums, notebooks and the whole sunny landscape perfectly still.',[e((32,144,59,169),200,'stove fire'),e((120,174,141,208),55,'tea steam')]),
'sakura-garden':('A few existing blossom clusters beyond the open window tremble almost imperceptibly in a light breeze. Tiny ripples animate the courtyard pond at the lower center outside. No new airborne petals or leaves, and all petals lying on the desk remain fixed.',[p([(222,177),(306,173),(363,195),(348,207),(244,204)],130,'garden pond')]),
'paris-attic':('Fine transparent steam curls above the blue floral coffee mug in the foreground right. The outermost small leaves on the balcony plant barely stir. Curtains, chairs and city skyline are completely still.',[e((413,221,439,274),60,'coffee steam'),e((290,130,331,159),80,'balcony leaves')]),
'underwater-study':('Very soft underwater light caustics evolve inside the broad blue panes at the center, without changing room exposure. No moving fish, schools, sharks or creatures: they remain frozen in the reference composition. A thin short steam wisp rises above the front-left tea cup.',[p([(230,71),(310,69),(309,119),(247,135),(224,125)],65,'underwater light center'),p([(335,65),(398,53),(406,100),(340,128)],65,'underwater light right'),e((100,244,125,288),45,'tea steam'),e((243,93,282,126),0,'preserve shark silhouette')]),
'moonlit-observatory':('Only a delicate transparent wisp rises above the foreground dark tea cup. Existing tiny flames in the low lanterns beside the balcony flicker gently. No twinkling stars, moving moon, cloud drift or telescope motion.',[e((443,226,469,272),55,'tea steam'),light((199,202,210,216),140,'left low flame'),light((422,184,434,201),130,'right low flame')]),
'frog-pond-studio':('Tiny calm water ripples pass around the existing lily pads outside the studio. Plants and pads remain anchored; no frogs jump and no new animals appear. Faint transparent tea steam rises above the front-left botanical cup.',[p([(270,181),(284,177),(296,171),(321,172),(328,181),(324,188),(287,187),(270,189)],35,'restrained open-water ripples excluding lily pads')]),
'kuromi-midnight-desk':('Only a very thin transparent wisp of warm drink steam curls directly above the black-and-lilac mug at the front right. Keep every plush character, lamp, star, moon and curtain absolutely still. Quiet believable heat motion, no magical effects.',[e((485,210,518,260),60,'mug steam')]),
'antique-workshop':('The sleeping cat on the lower-right chair breathes almost imperceptibly without repositioning. Preserve the original single clock pendulum completely still. Everything else, including hanging violins and the view, stays still.',[e((528,252,588,285),110,'sleeping cat torso')]),
'minecraft-cottage':('Tiny existing hearth flames flicker at the lower left and the foreground lantern flame flickers gently within its block-built enclosure. Very fine rain falls beyond the open doorway. Preserve rigid voxel geometry and original pixel texture, no smoothing or morphing.',[e((22,181,57,222),220,'hearth fire'),light((546,250,568,285),150,'front lantern'),r((384,54,432,144),120,'doorway rain')]),
'hateno-study':('Preserve all leaf and branch geometry. Only subtle filtered daylight varies over the existing nearest window leaves, using bounded luminance derived from the generated frames. The village, mountains, brush holder and room remain completely still; no steam.',[light((166,9,230,40),85,'filtered daylight on fixed window leaves')]),
'sumeru-akademiya':('The narrow distant waterfalls in the central green landscape flow gently downward within their exact existing channels. A few leaf tips on the hanging plant near the right edge barely tremble. All stonework, lamps and manuscripts are perfectly still.',[p([(397,124),(421,126),(419,159),(409,166),(399,149)],155,'distant waterfall')]),
'mage-archive':('The small existing fire in the far-right fireplace flickers quietly inside its stone opening. A very fine transparent steam wisp rises above the pale cup on the front-left desk. No moving books, papers, chandelier or meadow.',[e((557,211,587,247),200,'right hearth'),e((114,226,135,263),50,'tea steam')]),
'cyberpunk-rain-loft':('Fine exterior rain slides down the big glass panes. Very small ripples shimmer on the distant canal, while neon signs and towers remain constant. Keep all indoor objects still and do not animate vehicles or introduce people.',[p([(280,166),(343,162),(433,184),(426,200),(300,192)],100,'canal reflections')]),
'secret-door-study':('Only thin transparent steam curls upward a short distance above the owl mug on the foreground left. The little door stays closed, doll and decorations remain still, moon and stars do not move. Comfortable quiet atmosphere, no spooky surprises or magic.',[e((105,203,132,249),60,'owl mug steam')]),
'nevermore-study':('Very small candle flame flickers occur on the right side of the gothic room and in the left shelf candle cluster. Keep overall light absolutely stable. Rainclouds beyond the stained glass, sculptures, flowers and ink bottle remain still.',[light((551,164,561,192),170,'right candle'),light((523,140,531,161),150,'back candle'),light((18,122,30,137),120,'shelf candles')]),
'autumn-bakery':('A fine transparent steam curl rises above the foreground patterned coffee cup. The small candle in its glass holder at the left softly flickers. A few autumn leaf tips outside the window barely stir; no falling leaves or patrons.',[e((191,195,219,245),60,'coffee steam'),light((104,227,121,256),160,'glass candle')]),
'seoul-night-cafe':('Fine rain trails descend outside the broad central window. Faint steam rises above the white foreground cup. The small candle beside the cake flickers gently. The city reflections remain stable without flashing signs or people.',[e((184,187,210,237),60,'tea steam'),light((529,277,544,295),160,'glass candle')]),
'cloud-cafe':('The foreground white cup gives off one delicate transparent steam wisp. Soft distant clouds evolve almost imperceptibly in place, without camera travel. The sleeping orange-and-white cat on the left bench stays perfectly still, and all furniture and plants remain fixed.',[e((162,188,186,234),55,'tea steam'),e((307,143,409,177),65,'distant cloud contour')]),
 'tiny-mouse-house':('The tiny existing fire inside the miniature hearth near the lower center-left flickers gently. A delicate tea steam wisp rises above the blue-patterned cup at the front right. No mice or furniture move; preserve the miniature proportions exactly.',[e((522,208,552,258),60,'tea steam')]),
'woodland-treehouse':('Thin distant forest mist drifts almost imperceptibly between the trees beyond the central opening. One fine transparent tea steam wisp rises above the small cup near the desk center-right. Keep branches, bridge, houses, hanging lanterns and foreground leaves still.',[e((278,142,379,205),80,'distant forest mist'),e((383,217,406,253),55,'tea steam')]),
'aurora-cabin':('The existing northern lights form a very slow soft ripple within the green ribbons in the upper window. The small fire inside the stove at far left flickers naturally. All mountains, stars, lake and interior remain fixed; no exposure pulses.',[e((9,177,44,210),215,'stove flame')]),
'lighthouse-study':('Gentle ocean wavelets move naturally only within open sea below the distant sailboat, with safe margins from every cliff, rock, rail and telescope. Boats and rigid scenery remain fixed. A thin transparent tea steam wisp rises above the blue patterned cup near the left desk.',[p([(332,172),(400,171),(436,175),(440,187),(323,187)],145,'open sea below boat, clear of cliffs'),e((135,210,153,238),50,'tea steam')]),
'desert-casita':('Small ripples gently spread across two open-water portions of the shallow courtyard pool, with generous fixed margins around the entire stone fountain pedestal and tiled pool edges. Faint transparent tea steam rises above the patterned cup on the front right. Fountain stone, architecture and plants remain still.',[p([(275,217),(314,217),(314,235),(275,235)],150,'pool water left of stone pedestal'),p([(356,221),(386,221),(406,235),(356,235)],150,'pool water right of stone pedestal'),e((423,223,446,249),50,'tea steam')]),
'stationery-studio':('Only a thin transparent wisp of warm drink steam rises gently a short distance above the blue-patterned mug at the foreground right. All plants, vases, paper, stamps, curtains, instruments and shadows stay still.',[e((439,159,462,183),60,'mug steam above ceramic rim')]),
'thousand-sunny-study':('Small calm ocean wavelets move beyond the open shipboard balcony, entirely below the fixed horizon. A tiny warm flame flickers within the front-right lantern. Ship, rigging, sail, horizon, furniture and maps are completely fixed; no ship rocking.',[p([(241,128),(421,130),(417,162),(224,162)],150,'sea wavelets'),light((529,213,546,243),160,'lantern flame')]),
}
