/** Real Supabase Auth + DB integration. Run only when explicitly authorized.
 * No credentials/tokens are printed or written. All mutations are owned fixtures.
 * --realtime requires deployed invalidation migration. --load=N additionally
 * requires --approved-max=N; supported levels 100/250/500/1000. Never auto-ramp.
 */
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createServer } from 'node:http';
import { createRequire } from 'node:module';
import { writeFile } from 'node:fs/promises';
import { randomUUID, randomBytes } from 'node:crypto';
import { createBrowserApiHandler } from '../../../web/server/browser-api.mjs';
const require = createRequire(new URL('../../../web/package.json', import.meta.url));
const { createClient } = require('@supabase/supabase-js');
const PROJECT='lcfcjglybfeozyrjjikk', url=`https://${PROJECT}.supabase.co`;
const flags=new Set(process.argv.slice(2)), arg=name=>process.argv.slice(2).find(a=>a.startsWith(`--${name}=`))?.split('=').slice(1).join('=');
if (!flags.has('--run')) { console.log('Prepared only. Add --run after hosted fixture authorization; --realtime after migration. Load requires --load=100 --approved-max=100.'); process.exit(0); }
const load=Number(arg('load')??0), approved=Number(arg('approved-max')??0);
if(load && (![100,250,500,1000].includes(load)||load>approved||!flags.has('--realtime')))throw new Error('Load requires an explicitly approved supported bound and --realtime.');
const stamp=new Date().toISOString().replaceAll(':','-'), report={startedAt:new Date().toISOString(),project:PROJECT,transport:'loopback HTTP running actual web createBrowserApiHandler; real hosted Supabase Auth/DB',realtime:flags.has('--realtime'),load,checks:[],cleanup:[]};
const users=[],accounts=[],rooms=[],clients=[],channels=[];
let admin,server,origin,publicKey,serviceKey,currentStep='setup';
const fail=message=>{throw new Error(message);};
const check=(condition,message)=>{if(!condition)fail(message);};
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
// Supabase attaches its broadcast message UUID; it is transport metadata, not a Nooks record ID.
const safeHint=p=>p?.v===1&&Object.keys(p).every(k=>k==='v'||k==='id')&&(!Object.hasOwn(p,'id')||/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(p.id));
async function test(name,fn){currentStep=name;const start=performance.now();await fn();report.checks.push({name,passed:true,ms:Math.round(performance.now()-start)});console.log(`PASS ${name}`);}
const safeStatus=e=>({code:typeof e?.code==='string'&&/^[A-Z0-9_]+$/.test(e.code)?e.code:undefined,status:Number.isInteger(e?.status)?e.status:undefined});
async function api(user,tool,args,expected=200){const path=tool==='workspace'?'/api/workspace':`/api/tools/${tool}`;const response=await fetch(`${origin}${path}`,{method:tool==='workspace'?'GET':'POST',headers:{origin,'content-type':'application/json',...(user?{authorization:`Bearer ${user.token}`}:{})},...(tool==='workspace'?{}:{body:JSON.stringify(args??{})}),signal:AbortSignal.timeout(25000)});const body=await response.json();check(response.status===expected,`${tool}: expected HTTP ${expected}, received ${response.status}; code ${body?.error?.code??'none'}`);return body;}
async function subscribe(user,topic){const client=createClient(url,publicKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},realtime:{params:{eventsPerSecond:2}}});clients.push(client);await client.realtime.setAuth(user.token);const received=[];const channel=client.channel(topic,{config:{private:true,broadcast:{ack:true,self:false}}}).on('broadcast',{event:'invalidate'},event=>received.push(event.payload));channels.push(channel);const status=await new Promise(resolve=>{const timer=setTimeout(()=>resolve('TIMEOUT'),15000);channel.subscribe(state=>{if(['SUBSCRIBED','CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(state)){clearTimeout(timer);resolve(state);}});});return {client,channel,status,received};}
async function cleanup(){
 for(const client of clients){try{await client.removeAllChannels();client.realtime.disconnect();}catch{report.cleanup.push({type:'socket',ok:false});}}
 if(admin){
  // Rooms first, because owner_id intentionally does not cascade from account.
  for(const id of rooms){const {error}=await admin.from('nooks_rooms').delete().eq('id',id);report.cleanup.push({type:'fixture-room',id,ok:!error,...safeStatus(error)});}
  // Account IDs are resolved exclusively from users created by this execution.
  for(const user of users){const {data,error}=await admin.from('nooks_accounts').select('id').eq('auth_user_id',user.id);if(error)report.cleanup.push({type:'account-lookup',id:user.id,ok:false,...safeStatus(error)});for(const row of data??[]){if(!accounts.includes(row.id))accounts.push(row.id);}}
  for(const id of accounts){const {error}=await admin.from('nooks_accounts').delete().eq('id',id);report.cleanup.push({type:'fixture-account',id,ok:!error,...safeStatus(error)});}
  for(const user of users){if(user.token)try{await admin.auth.admin.signOut(user.token,'global');}catch{}const {error}=await admin.auth.admin.deleteUser(user.id);report.cleanup.push({type:'fixture-auth-user',id:user.id,ok:!error,...safeStatus(error)});}
 }
 if(server)await new Promise(resolve=>server.close(resolve));
}
try{
 const {stdout}=await promisify(execFile)('supabase',['projects','api-keys','--project-ref',PROJECT,'--output','json'],{maxBuffer:2*1024*1024});
 const parsed=JSON.parse(stdout),keys=Array.isArray(parsed)?parsed:parsed.api_keys??parsed.keys;
 check(Array.isArray(keys),'CLI key result has unexpected shape');
 publicKey=keys.find(k=>k.name==='anon')?.api_key??keys.find(k=>k.api_key?.startsWith('sb_publishable_'))?.api_key;
 serviceKey=keys.find(k=>k.name==='service_role')?.api_key??keys.find(k=>k.api_key?.startsWith('sb_secret_'))?.api_key;
 check(publicKey&&serviceKey,'Required project keys unavailable');
 admin=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});
 server=createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin=`http://127.0.0.1:${server.address().port}`;
 const handler=createBrowserApiHandler({env:{SUPABASE_URL:url,SUPABASE_PUBLISHABLE_KEY:publicKey,SUPABASE_SERVICE_KEY:serviceKey,NOOKS_PUBLIC_URL:origin},allowedOrigins:[origin],logger:()=>{}});
 server.on('request',handler);
 await test('two distinct confirmed ephemeral users with real JWTs',async()=>{
  for(const label of ['a','b']){const email=`nooks-hosted-${randomUUID()}-${label}@example.invalid`,password=randomBytes(30).toString('base64url');const {data,error}=await admin.auth.admin.createUser({email,password,email_confirm:true});check(!error&&data?.user?.id,`Admin fixture creation failed (${error?.status??'unknown'})`);const user={id:data.user.id};users.push(user);const client=createClient(url,publicKey,{auth:{persistSession:false,autoRefreshToken:false}});const signed=await client.auth.signInWithPassword({email,password});check(!signed.error&&signed.data.session?.access_token,'Fixture password authentication failed');user.token=signed.data.session.access_token;await api(user,'workspace');const mapped=await admin.from('nooks_accounts').select('id').eq('auth_user_id',user.id).single();check(!mapped.error&&mapped.data?.id,'Fixture account resolution failed');user.account=mapped.data.id;accounts.push(user.account);}
  check(users[0].id!==users[1].id&&users[0].account!==users[1].account&&users[0].token!==users[1].token,'Fixture identities must be distinct');
 });
 const [a,b]=users,note=`qa-${randomUUID()}`;
 await test('unauthenticated HTTP request denied',()=>api(null,'workspace',null,401));
 await test('private notes isolated between authenticated accounts',async()=>{await api(a,'artifact_save',{artifact:{id:note,kind:'note',title:'Ephemeral QA note',content:'Private fixture A'}});await api(b,'artifact_get',{artifactId:note},404);await api(b,'artifact_save',{artifact:{id:note,kind:'note',title:'Ephemeral QA note',content:'Private fixture B'}});const own=await api(a,'artifact_get',{artifactId:note});check(own.artifact.content==='Private fixture A','Note isolation failed');});
 await test('concurrent compare-and-swap accepts one edit, preserves loser',async()=>{const outcomes=await Promise.all(['first','second'].map(content=>fetch(`${origin}/api/tools/note_update`,{method:'POST',headers:{origin,'content-type':'application/json',authorization:`Bearer ${a.token}`},body:JSON.stringify({artifactId:note,expectedRevision:1,content})})));check(outcomes.map(r=>r.status).sort().join(',')==='200,409','Concurrent edits did not produce one success and one conflict');const own=await api(a,'artifact_get',{artifactId:note});check(['first','second'].includes(own.artifact.content)&&own.artifact.revision===2,'Unexpected note after CAS');});
 await test('authenticated Data API cannot read other account notes',async()=>{const response=await fetch(`${url}/rest/v1/nooks_artifacts?account_id=eq.${a.account}&select=id`,{headers:{apikey:publicKey,authorization:`Bearer ${b.token}`}});const data=await response.json();check(response.ok&&Array.isArray(data)&&data.length===0,'RLS cross-account read not empty');});
 let privateId,publicId;
 await test('private room create retry creates exactly one room',async()=>{const args={requestId:randomUUID(),title:'Ephemeral QA private',roomId:'rainy-library',visibility:'private'};const first=await api(a,'nook_create',args);privateId=first.nook.id;rooms.push(privateId);const retry=await api(a,'nook_create',args);check(retry.nook.id===privateId&&retry.duplicate===true,'Room create retry not idempotent');});
 await test('private room requires invite for join and snapshot',async()=>{await api(b,'nook_join',{nookId:privateId},403);await api(b,'nook_snapshot',{nookId:privateId},403);const list=await api(b,'nooks_list');check(!list.nooks.some(n=>n.id===privateId),'Private fixture leaked into directory');});
 if(flags.has('--realtime'))await test('nonmember denied private Realtime subscription',async()=>{const denied=await subscribe(b,`nook:${privateId}`);check(denied.status==='CHANNEL_ERROR','Nonmember channel did not return authorization rejection');await denied.client.removeAllChannels();denied.client.realtime.disconnect();});
 await test('invitation acceptance and retry consume one use',async()=>{const invite=(await api(a,'nook_invite_create',{nookId:privateId,maxUses:1})).invite;await api(b,'nook_invite_accept',{token:invite.token});const retry=await api(b,'nook_invite_accept',{token:invite.token});check(retry.duplicate===true,'Invitation retry not idempotent');const list=await api(a,'nook_invites_list',{nookId:privateId});check(list.invites.find(i=>i.id===invite.id)?.uses===1,'Invitation retry consumed another use');check(!JSON.stringify(list).includes(invite.token),'Invitation secret leaked into metadata');await api(b,'nook_invites_list',{nookId:privateId},403);});
 let subscription;
 if(flags.has('--realtime'))await test('member receives content-free invalidation after other user changes profile',async()=>{subscription=await subscribe(b,`nook:${privateId}`);check(subscription.status==='SUBSCRIBED','Member subscription failed');await sleep(2200);await api(a,'profile_update',{displayName:'Ephemeral QA host',avatar:0});for(let i=0;i<40&&!subscription.received.length;i++)await sleep(250);check(subscription.received.length>0,'No cross-user invalidation delivered');check(subscription.received.every(safeHint),`Invalidation payload contains unexpected data; shape ${JSON.stringify(subscription.received.map(p=>({type:typeof p,keys:Object.keys(p??{}),version:p?.v,innerKeys:Object.keys(p?.payload??{})})))}`);});
 await test('presence updates online count without study credits',async()=>{await api(b,'nook_presence',{nookId:privateId});const snapshot=await api(a,'nook_snapshot',{nookId:privateId});check(snapshot.onlineCount===2&&snapshot.memberCount===2,'Two-user presence missing');check(snapshot.leaderboard.every(m=>m.focusMinutes===0),'Presence awarded focus credits');});
 await test('leaving private room immediately forbids fetch and presence',async()=>{await api(b,'nook_leave',{nookId:privateId});await api(b,'nook_snapshot',{nookId:privateId},403);await api(b,'nook_presence',{nookId:privateId},403);});
 if(flags.has('--realtime'))await test('removed member denied a fresh subscription',async()=>{if(subscription){await subscription.client.removeAllChannels();subscription.client.realtime.disconnect();}const denied=await subscribe(b,`nook:${privateId}`);check(denied.status==='CHANNEL_ERROR','Removed member reconnect was not denied');await denied.client.removeAllChannels();denied.client.realtime.disconnect();});
 await test('public directory membership and owner-only controls',async()=>{const created=await api(a,'nook_create',{requestId:randomUUID(),title:'Ephemeral QA public',roomId:'rainy-library',visibility:'public'});publicId=created.nook.id;rooms.push(publicId);const directory=await api(b,'nooks_list');check(directory.nooks.some(n=>n.id===publicId),'Public fixture absent from directory');await api(b,'nook_snapshot',{nookId:publicId},403);await api(b,'nook_join',{nookId:publicId});await api(b,'nook_snapshot',{nookId:publicId});await api(b,'nook_archive',{nookId:publicId},403);});
 await test('server-clock focus completion retry awards credit once',async()=>{const started=await api(b,'focus_start',{minutes:1,nookId:publicId});console.log('Waiting 62 seconds for real server-clock focus fixture.');await sleep(31000);await sleep(31000);const args={sessionId:started.focusSession.id};await api(b,'focus_complete',args);const retry=await api(b,'focus_complete',args);check(retry.duplicate===true&&retry.workspace.stats.focusMinutes===1,'Focus retry duplicated personal credit');const snapshot=await api(a,'nook_snapshot',{nookId:publicId});check(snapshot.leaderboard.find(m=>m.id===b.account)?.focusMinutes===1,'Shared focus credit missing or duplicated');});
 if(load)await test(`bounded ${load} independent authenticated WebSocket connections`,async()=>{const start=performance.now(),results=[];for(let offset=0;offset<load;offset+=10){const batch=await Promise.all(Array.from({length:Math.min(10,load-offset)},()=>subscribe(b,`nook:${publicId}`)));results.push(...batch);if(batch.some(s=>s.status!=='SUBSCRIBED'))break;await sleep(250);}report.loadResult={requested:load,connected:results.filter(r=>r.status==='SUBSCRIBED').length,elapsedMs:Math.round(performance.now()-start)};check(report.loadResult.connected===load,'Connection bound not reached; stopped ramp');await sleep(2200);await api(a,'profile_update',{displayName:'Ephemeral load host',avatar:1});for(let i=0;i<40&&results.some(r=>!r.received.length);i++)await sleep(250);report.loadResult.received=results.filter(r=>r.received.length).length;check(report.loadResult.received===load,'Not all connected clients received invalidation');check(results.every(r=>r.received.every(safeHint)),'Unexpected load payload');});
 await test('archive retry preserves closure and removes access',async()=>{await api(a,'nook_archive',{nookId:publicId});const retry=await api(a,'nook_archive',{nookId:publicId});check(retry.duplicate===true,'Archive retry not idempotent');await api(b,'nook_snapshot',{nookId:publicId},403);});
 report.passed=true;
}catch(error){report.passed=false;report.checks.push({name:currentStep,passed:false,error:typeof error.message==='string'&&!/Bearer |eyJ|sb_secret_|sb_publishable_|password|access_token/i.test(error.message)?error.message.slice(0,400):'Redacted execution error',...safeStatus(error)});console.log(`FAIL ${currentStep}`);process.exitCode=1;}
finally{await cleanup();report.finishedAt=new Date().toISOString();if(report.cleanup.some(c=>!c.ok)){report.passed=false;process.exitCode=1;}const path=new URL(`./report-${stamp}.json`,import.meta.url);await writeFile(path,JSON.stringify(report,null,2)+'\n');console.log(`Report: ${path.pathname}`);console.log(`Checks passed: ${report.checks.filter(c=>c.passed).length}; cleanup failures: ${report.cleanup.filter(c=>!c.ok).length}`);}
