begin;
do $$
declare owner_id uuid:=gen_random_uuid(); guest_id uuid:=gen_random_uuid(); outsider_id uuid:=gen_random_uuid(); result jsonb; sid uuid; item jsonb; rev bigint;
begin
 insert into public.nooks_accounts(id) values(owner_id),(guest_id),(outsider_id);
 insert into public.nooks_workspaces(account_id,document) values(owner_id,jsonb_build_object('organization',jsonb_build_object('courses',jsonb_build_array(jsonb_build_object('id','test-folder','title','Collaboration test','archived',false)))));
 insert into public.nooks_artifacts(account_id,id,kind,payload,position) values(owner_id,'inside','note','{"id":"inside","kind":"note","title":"Inside","content":"Original","courseId":"test-folder","revision":1}',1),(owner_id,'outside','note','{"id":"outside","kind":"note","title":"Private","content":"Must not leak","revision":1}',2);
 result:=public.nooks_library_action(owner_id,'create','{"kind":"course","targetId":"test-folder","permission":"view","tokenHash":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}'); sid:=(result->'share'->>'id')::uuid;
 begin perform public.nooks_library_action(outsider_id,'get',jsonb_build_object('shareId',sid)); raise exception 'Unauthorized read accepted'; exception when insufficient_privilege then null; end;
 begin perform public.nooks_library_action(guest_id,'join',jsonb_build_object('shareId',sid,'tokenHash',repeat('b',64))); raise exception 'Wrong invitation accepted'; exception when insufficient_privilege then null; end;
 result:=public.nooks_library_action(guest_id,'join',jsonb_build_object('shareId',sid,'tokenHash',repeat('a',64)));
 if jsonb_array_length(result->'materials')<>1 or result->'materials'->0->>'id'<>'inside' or result->'share'->>'permission'<>'view' then raise exception 'Scoped read failed'; end if;
 item:='{"id":"inside","kind":"note","title":"Inside","content":"Changed"}';
 begin perform public.nooks_library_action(guest_id,'save',jsonb_build_object('shareId',sid,'artifact',item,'expectedRevision',1)); raise exception 'View edit accepted'; exception when insufficient_privilege then null; end;
 begin perform public.nooks_library_action(guest_id,'comment',jsonb_build_object('shareId',sid,'artifactId','inside','body','Hello')); raise exception 'View comment accepted'; exception when insufficient_privilege then null; end;
 result:=public.nooks_library_action(owner_id,'create','{"kind":"course","targetId":"test-folder","permission":"comment","tokenHash":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"}');
 result:=public.nooks_library_action(guest_id,'comment',jsonb_build_object('shareId',sid,'artifactId','inside','body','Hello'));
 if jsonb_array_length(result->'comments')<>1 then raise exception 'Comment save failed'; end if;
 begin perform public.nooks_library_action(guest_id,'save',jsonb_build_object('shareId',sid,'artifact',item,'expectedRevision',1)); raise exception 'Comment edit accepted'; exception when insufficient_privilege then null; end;
 begin perform public.nooks_library_action(guest_id,'comment',jsonb_build_object('shareId',sid,'artifactId','outside','body','Hello')); raise exception 'Comment scope bypassed'; exception when insufficient_privilege then null; end;
 result:=public.nooks_library_action(owner_id,'create','{"kind":"course","targetId":"test-folder","permission":"edit","tokenHash":"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"}');
 result:=public.nooks_library_action(guest_id,'save',jsonb_build_object('shareId',sid,'artifact',item,'expectedRevision',1));
 if result->'artifact'->>'content'<>'Changed' or (result->'artifact'->>'revision')::integer<>2 then raise exception 'Collaborative edit failed'; end if;
 begin perform public.nooks_library_action(guest_id,'save',jsonb_build_object('shareId',sid,'artifact',item,'expectedRevision',1)); raise exception 'Stale edit accepted'; exception when serialization_failure then null; end;
 begin perform public.nooks_library_action(guest_id,'save',jsonb_build_object('shareId',sid,'artifact',item||'{"id":"outside"}'::jsonb,'expectedRevision',1)); raise exception 'Edit scope bypassed'; exception when insufficient_privilege then null; end;
 result:=public.nooks_library_action(guest_id,'save',jsonb_build_object('shareId',sid,'artifact','{"id":"new-note","kind":"note","title":"New note","content":"Added by editor"}'::jsonb));
 if jsonb_array_length(result->'materials')<>2 or result->'artifact'->>'courseId'<>'test-folder' then raise exception 'Add material failed'; end if;
 result:=public.nooks_workspace_read(owner_id);
 if result->'workspace'->'organization'->'noteRevisions'->0->>'content'<>'Original' then raise exception 'Note history lost'; end if;
 if jsonb_array_length(result->'workspace'->'artifacts')<>3 or (result->>'revision')::integer<>2 then raise exception 'Owner workspace sync failed'; end if;
 begin perform public.nooks_library_action(guest_id,'revoke',jsonb_build_object('shareId',sid)); raise exception 'Nonowner revoke accepted'; exception when insufficient_privilege then null; end;
 perform public.nooks_library_action(owner_id,'revoke',jsonb_build_object('shareId',sid));
 begin perform public.nooks_library_action(guest_id,'get',jsonb_build_object('shareId',sid)); raise exception 'Revoked share readable'; exception when no_data_found then null; end;
 perform public.nooks_library_action(owner_id,'create','{"kind":"course","targetId":"test-folder","permission":"view","tokenHash":"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"}');
 begin perform public.nooks_library_action(guest_id,'get',jsonb_build_object('shareId',sid)); raise exception 'Old member regained access'; exception when insufficient_privilege then null; end;
 begin perform public.nooks_library_action(guest_id,'join',jsonb_build_object('shareId',sid,'tokenHash',repeat('a',64))); raise exception 'Old invitation accepted'; exception when insufficient_privilege then null; end;
 if has_function_privilege('authenticated','public.nooks_library_action(uuid,text,jsonb)','EXECUTE') or has_function_privilege('anon','public.nooks_library_action(uuid,text,jsonb)','EXECUTE') then raise exception 'RPC publicly exposed'; end if;
 result:=public.nooks_library_action(owner_id,'create','{"kind":"material","targetId":"outside","permission":"edit","tokenHash":"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"}'); sid:=(result->'share'->>'id')::uuid;
 result:=public.nooks_library_action(guest_id,'join',jsonb_build_object('shareId',sid,'tokenHash',repeat('e',64)));
 if jsonb_array_length(result->'materials')<>1 or result->'materials'->0->>'id'<>'outside' then raise exception 'File scope leaked'; end if;
 begin perform public.nooks_library_action(guest_id,'save',jsonb_build_object('shareId',sid,'artifact',item,'expectedRevision',2)); raise exception 'File scope edit bypassed'; exception when insufficient_privilege then null; end;
 begin perform public.nooks_library_action(guest_id,'save',jsonb_build_object('shareId',sid,'artifact','{"id":"another-note","kind":"note","title":"Another","content":"Wrong scope"}'::jsonb)); raise exception 'File share accepted new material'; exception when insufficient_privilege then null; end;
 result:=public.nooks_library_action(guest_id,'save',jsonb_build_object('shareId',sid,'artifact','{"id":"outside","kind":"note","title":"Shared file","content":"Updated"}'::jsonb,'expectedRevision',1));
 if result->'artifact'->>'content'<>'Updated' or (result->'artifact'->>'revision')::integer<>2 then raise exception 'File edit failed'; end if;
 raise notice 'Library collaboration assertions passed';
end $$;
rollback;
