import type { CSSProperties } from 'react';

export type SpaceTheme = 'botanical' | 'moonlight' | 'sunrise' | 'lavender' | 'sky';
export type RoomCategory = 'cozy' | 'nature' | 'city' | 'elsewhere';
export type RoomStyle = 'cinematic' | 'anime' | 'illustrated' | 'watercolor' | 'pixel' | 'dreamlike' | 'photoreal';
export type RoomMood = 'rain' | 'snow' | 'petals' | 'stars' | 'sun' | 'sea' | 'city' | 'none';
export type RoomSurfaceSegment = readonly [number, number, number, number];
export interface RoomScene { id: string; title: string; caption: string; category: RoomCategory; style: RoomStyle; image: string; thumbnail?: string; collection?: string; fandom?: boolean; theme: SpaceTheme; mood: RoomMood; width: number; height: number; segments: readonly RoomSurfaceSegment[] }
export type SpaceCompanion = 'sleepy-dog' | 'sprout' | 'cat' | 'none' | 'bunny' | 'fox' | 'capybara' | 'red-panda' | 'owl' | 'turtle' | 'bear' | 'ghost';
export interface WorkspaceSpace {
  name: string;
  tagline: string;
  theme: SpaceTheme;
  room?: RoomId;
  accent: string;
  companion: SpaceCompanion;
  layout: 'calm' | 'focused';
  decorations: ('sparkles' | 'stickers')[];
  backgroundImage?: string;
}
export interface SpaceStats { xp: number; level: number; streak: number; focusMinutes: number }
export interface SharedSpace { id: string; url?: string; createdAt: string; space: WorkspaceSpace; description: string; stats?: SpaceStats; roomDisplay?: { roomId: string; placed: string[] } }
export const defaultSpace: WorkspaceSpace = { name: 'My study nook', tagline: 'A little focus. A little growth. A lot of possibility.', theme: 'botanical', accent: '#8bc8a7', companion: 'sleepy-dog', layout: 'calm', decorations: ['sparkles'] };
export const legacyRoomScenes = [
  {
    "id": "rainy-library",
    "title": "Rainy Library",
    "caption": "Amber lamps & city rain",
    "category": "cozy",
    "image": "/images/lofi-rainy-library.webp",
    "theme": "botanical",
    "mood": "rain",
    "width": 1672,
    "height": 941,
    "style": "cinematic",
    "segments": []
  },
  {
    "id": "midnight-train",
    "title": "Night Train",
    "caption": "Moonlit countryside & quiet rails",
    "category": "elsewhere",
    "image": "/images/lofi-midnight-train.webp",
    "theme": "sky",
    "mood": "stars",
    "width": 1672,
    "height": 941,
    "style": "cinematic",
    "segments": []
  },
  {
    "id": "sakura-garden",
    "title": "Cherry Garden",
    "caption": "Petals & afternoon light",
    "category": "nature",
    "image": "/images/lofi-sakura-garden.webp",
    "theme": "sunrise",
    "mood": "petals",
    "width": 1672,
    "height": 941,
    "style": "cinematic",
    "segments": []
  },
  {
    "id": "seaside-studio",
    "title": "Seaside Studio",
    "caption": "Salt air, linen & a blue horizon",
    "category": "nature",
    "image": "/images/lofi-seaside-studio.webp",
    "theme": "sky",
    "mood": "sea",
    "width": 1672,
    "height": 940,
    "style": "cinematic",
    "segments": []
  },
  {
    "id": "alpine-cabin",
    "title": "Snow Cabin",
    "caption": "Mountain snow & a crackling fire",
    "category": "cozy",
    "image": "/images/lofi-alpine-cabin.webp",
    "theme": "moonlight",
    "mood": "snow",
    "width": 1672,
    "height": 941,
    "style": "cinematic",
    "segments": []
  },
  {
    "id": "autumn-bookshop",
    "title": "Autumn Bookshop",
    "caption": "Rain, copper leaves & old pages",
    "category": "cozy",
    "image": "/images/lofi-autumn-bookshop.webp",
    "theme": "sunrise",
    "mood": "rain",
    "width": 1672,
    "height": 941,
    "style": "cinematic",
    "segments": []
  },
  {
    "id": "moonlit-observatory",
    "title": "Hilltop Observatory",
    "caption": "A quiet desk beneath the stars",
    "category": "elsewhere",
    "image": "/images/lofi-moonlit-observatory.webp",
    "theme": "moonlight",
    "mood": "stars",
    "width": 1672,
    "height": 941,
    "style": "cinematic",
    "segments": []
  },
  {
    "id": "sunlit-greenhouse",
    "title": "Sunlit Greenhouse",
    "caption": "Golden light through leafy glass",
    "category": "nature",
    "image": "/images/lofi-sunlit-greenhouse.webp",
    "theme": "botanical",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "style": "cinematic",
    "segments": []
  },
  {
    "id": "neon-tokyo",
    "title": "Rooftop Tokyo",
    "caption": "Rooftop quiet & distant city lights",
    "category": "city",
    "image": "/images/lofi-neon-tokyo.webp",
    "theme": "lavender",
    "mood": "city",
    "width": 1672,
    "height": 941,
    "style": "cinematic",
    "segments": []
  },
  {
    "id": "paris-attic",
    "title": "Paris Attic",
    "caption": "Rooftops, linen & first light",
    "category": "city",
    "image": "/images/lofi-paris-attic.webp",
    "theme": "sunrise",
    "mood": "sun",
    "style": "cinematic",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "kyoto-teahouse",
    "title": "Kyoto Teahouse",
    "caption": "Tatami, tea & bamboo rain",
    "category": "nature",
    "image": "/images/lofi-kyoto-teahouse.webp",
    "theme": "botanical",
    "mood": "rain",
    "style": "cinematic",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "brooklyn-loft",
    "title": "Brooklyn Loft",
    "caption": "Vinyl, brick & afternoon sun",
    "category": "city",
    "image": "/images/lofi-brooklyn-loft.webp",
    "theme": "sunrise",
    "mood": "sun",
    "style": "cinematic",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "cloud-bedroom",
    "title": "Cloud Bedroom",
    "caption": "Soft pink, ribbons & daydreams",
    "category": "cozy",
    "image": "/images/lofi-cloud-bedroom.webp",
    "theme": "lavender",
    "mood": "sun",
    "style": "cinematic",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "oxford-library",
    "title": "Oak Library",
    "caption": "Oak shelves & rainy windows",
    "category": "cozy",
    "image": "/images/lofi-oxford-library.webp",
    "theme": "moonlight",
    "mood": "rain",
    "style": "cinematic",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "lighthouse-study",
    "title": "Lighthouse Desk",
    "caption": "Salt air & a distant horizon",
    "category": "elsewhere",
    "image": "/images/lofi-lighthouse-study.webp",
    "theme": "sky",
    "mood": "sea",
    "style": "illustrated",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "tropical-veranda",
    "title": "Monsoon Veranda",
    "caption": "Rain on palm leaves",
    "category": "nature",
    "image": "/images/lofi-tropical-veranda.webp",
    "theme": "botanical",
    "mood": "rain",
    "style": "cinematic",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "mossy-watermill",
    "title": "Moss Watermill",
    "caption": "A stream through the forest",
    "category": "nature",
    "image": "/images/lofi-mossy-watermill.webp",
    "theme": "botanical",
    "mood": "sun",
    "style": "illustrated",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "aurora-cabin",
    "title": "Aurora Cabin",
    "caption": "Arctic quiet & a warm blanket",
    "category": "nature",
    "image": "/images/lofi-aurora-cabin.webp",
    "theme": "sky",
    "mood": "stars",
    "style": "dreamlike",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "autumn-camper",
    "title": "Autumn Camper",
    "caption": "Autumn hills from your camper",
    "category": "elsewhere",
    "image": "/images/lofi-autumn-camper.webp",
    "theme": "sunrise",
    "mood": "sun",
    "style": "anime",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "ricefield-porch",
    "title": "Ricefield Porch",
    "caption": "An open porch in late summer",
    "category": "nature",
    "image": "/images/lofi-ricefield-porch.webp",
    "theme": "botanical",
    "mood": "sun",
    "style": "anime",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "lakeside-boathouse",
    "title": "Lakeside Boathouse",
    "caption": "Still water & summer light",
    "category": "nature",
    "image": "/images/lofi-lakeside-boathouse.webp",
    "theme": "sky",
    "mood": "sea",
    "style": "watercolor",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "castle-study",
    "title": "Castle Tower",
    "caption": "A desk above the sleeping town",
    "category": "elsewhere",
    "image": "/images/lofi-castle-study.webp",
    "theme": "moonlight",
    "mood": "stars",
    "style": "illustrated",
    "width": 1672,
    "height": 940,
    "segments": []
  },
  {
    "id": "desert-casita",
    "title": "Desert Casita",
    "caption": "Terracotta walls & sunset mesas",
    "category": "nature",
    "image": "/images/lofi-desert-casita.webp",
    "theme": "sunrise",
    "mood": "sun",
    "style": "cinematic",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "underwater-study",
    "title": "Reef Study",
    "caption": "Blue depths & amber lamps",
    "category": "elsewhere",
    "image": "/images/lofi-underwater-study.webp",
    "theme": "sky",
    "mood": "sea",
    "style": "dreamlike",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "floating-airship",
    "title": "Cloud Airship",
    "caption": "Brass windows above the clouds",
    "category": "elsewhere",
    "image": "/images/lofi-floating-airship.webp",
    "theme": "sunrise",
    "mood": "sun",
    "style": "dreamlike",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "moon-base",
    "title": "Moon Base",
    "caption": "A quiet desk with an Earth view",
    "category": "elsewhere",
    "image": "/images/lofi-moon-base.webp",
    "theme": "moonlight",
    "mood": "stars",
    "style": "cinematic",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "woodland-treehouse",
    "title": "Woodland Treehouse",
    "caption": "Canopy light & timber shelves",
    "category": "nature",
    "image": "/images/lofi-woodland-treehouse.webp",
    "theme": "botanical",
    "mood": "sun",
    "style": "illustrated",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "lavender-cottage",
    "title": "Lavender Cottage",
    "caption": "Provence fields in watercolor",
    "category": "cozy",
    "image": "/images/lofi-lavender-cottage.webp",
    "theme": "lavender",
    "mood": "sun",
    "style": "watercolor",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "canal-apartment",
    "title": "Canal Apartment",
    "caption": "Amsterdam dusk & rain reflections",
    "category": "city",
    "image": "/images/lofi-canal-apartment.webp",
    "theme": "moonlight",
    "mood": "rain",
    "style": "anime",
    "width": 1672,
    "height": 941,
    "segments": []
  },
  {
    "id": "night-campus",
    "title": "Night Campus",
    "caption": "A pixel library after dark",
    "category": "cozy",
    "image": "/images/lofi-night-campus.webp",
    "theme": "moonlight",
    "mood": "stars",
    "style": "pixel",
    "width": 1672,
    "height": 941,
    "segments": []
  },
{
  "id": "mosslight-dungeon",
  "title": "Mosslight Dungeon",
  "caption": "Crystal pools & candlelit stone",
  "category": "elsewhere",
  "image": "/images/lofi-mosslight-dungeon.webp",
  "theme": "moonlight",
  "mood": "none",
  "style": "illustrated",
  "width": 1672,
  "height": 941,
  "segments": []
}
] as const satisfies readonly RoomScene[];
// The approved discovery catalog. Legacy scenes remain resolvable for saved work.
export const roomScenes = [
  {
    "id": "rainy-library",
    "title": "Rainy Library",
    "caption": "Amber desk lamps, enormous rain-streaked windows, blue city outside",
    "category": "cozy",
    "style": "cinematic",
    "image": "/images/nooks-50/rainy-library.webp",
    "thumbnail": "/images/nooks-50/thumbs/rainy-library.webp",
    "theme": "sky",
    "mood": "rain",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cozy",
    "fandom": false
  },
  {
    "id": "howls-moving-study",
    "title": "Howl’s Moving Castle — Moving Study",
    "caption": "A warm, cluttered castle study with a magical doorway and rolling hills outside",
    "category": "elsewhere",
    "style": "anime",
    "image": "/images/nooks-50/howls-moving-study.webp",
    "thumbnail": "/images/nooks-50/thumbs/howls-moving-study.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Anime",
    "fandom": true
  },
  {
    "id": "gryffindor-common-room",
    "title": "Hogwarts — Gryffindor Common Room",
    "caption": "Scarlet armchairs, a huge fireplace, worn trunks and warm evening light",
    "category": "cozy",
    "style": "cinematic",
    "image": "/images/nooks-50/gryffindor-common-room.webp",
    "thumbnail": "/images/nooks-50/thumbs/gryffindor-common-room.webp",
    "theme": "botanical",
    "mood": "none",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Wizarding",
    "fandom": true
  },
  {
    "id": "neon-tokyo",
    "title": "Tokyo Rain Apartment",
    "caption": "A compact high-floor apartment, wet neon streets and a warm task lamp",
    "category": "city",
    "style": "anime",
    "image": "/images/nooks-50/neon-tokyo.webp",
    "thumbnail": "/images/nooks-50/thumbs/neon-tokyo.webp",
    "theme": "sky",
    "mood": "rain",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "City",
    "fandom": false
  },
  {
    "id": "alpine-cabin",
    "title": "Comfy Cabin",
    "caption": "A timber cabin, deep armchair, firelight and snow beyond the glass",
    "category": "cozy",
    "style": "illustrated",
    "image": "/images/nooks-50/alpine-cabin.webp",
    "thumbnail": "/images/nooks-50/thumbs/alpine-cabin.webp",
    "theme": "botanical",
    "mood": "snow",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cozy",
    "fandom": false
  },
  {
    "id": "totoro-forest-window",
    "title": "My Neighbor Totoro — Forest Window",
    "caption": "A countryside desk facing an enormous camphor tree and a soft rainy garden",
    "category": "nature",
    "style": "anime",
    "image": "/images/nooks-50/totoro-forest-window.webp",
    "thumbnail": "/images/nooks-50/thumbs/totoro-forest-window.webp",
    "theme": "sky",
    "mood": "rain",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Anime",
    "fandom": true
  },
  {
    "id": "slytherin-common-room",
    "title": "Hogwarts — Slytherin Common Room",
    "caption": "An emerald-lit stone lounge under the lake, with silver details and passing silhouettes",
    "category": "elsewhere",
    "style": "cinematic",
    "image": "/images/nooks-50/slytherin-common-room.webp",
    "thumbnail": "/images/nooks-50/thumbs/slytherin-common-room.webp",
    "theme": "moonlight",
    "mood": "none",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Wizarding",
    "fandom": true
  },
  {
    "id": "kikis-bakery-attic",
    "title": "Kiki’s Delivery Service — Bakery Attic",
    "caption": "A small attic desk above a seaside bakery, with bread baskets and rooftops",
    "category": "cozy",
    "style": "anime",
    "image": "/images/nooks-50/kikis-bakery-attic.webp",
    "thumbnail": "/images/nooks-50/thumbs/kikis-bakery-attic.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Anime",
    "fandom": true
  },
  {
    "id": "midnight-train",
    "title": "Midnight Sleeper Train",
    "caption": "A lamplit sleeper compartment with rain sliding past and changing landscapes",
    "category": "elsewhere",
    "style": "anime",
    "image": "/images/nooks-50/midnight-train.webp",
    "thumbnail": "/images/nooks-50/thumbs/midnight-train.webp",
    "theme": "sky",
    "mood": "rain",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Travel",
    "fandom": false
  },
  {
    "id": "hufflepuff-common-room",
    "title": "Hogwarts — Hufflepuff Common Room",
    "caption": "Round windows, honey-colored wood, plants, copper kettles and a hearth",
    "category": "cozy",
    "style": "illustrated",
    "image": "/images/nooks-50/hufflepuff-common-room.webp",
    "thumbnail": "/images/nooks-50/thumbs/hufflepuff-common-room.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Wizarding",
    "fandom": true
  },
  {
    "id": "ravenclaw-tower",
    "title": "Hogwarts — Ravenclaw Tower",
    "caption": "Airy blue-and-bronze study, arched windows, stars and mountain views",
    "category": "elsewhere",
    "style": "cinematic",
    "image": "/images/nooks-50/ravenclaw-tower.webp",
    "thumbnail": "/images/nooks-50/thumbs/ravenclaw-tower.webp",
    "theme": "moonlight",
    "mood": "stars",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Wizarding",
    "fandom": true
  },
  {
    "id": "stardew-farmhouse",
    "title": "Stardew Valley — Farmhouse Desk",
    "caption": "A pixel-art farmhouse desk beside crop plots and a snug kitchen",
    "category": "cozy",
    "style": "pixel",
    "image": "/images/nooks-50/stardew-farmhouse.webp",
    "thumbnail": "/images/nooks-50/thumbs/stardew-farmhouse.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cozy games",
    "fandom": true
  },
  {
    "id": "spirited-bathhouse",
    "title": "Spirited Away — Bathhouse Study",
    "caption": "A lantern-lit desk above a misty bathhouse courtyard, quieter than the busy film scenes",
    "category": "elsewhere",
    "style": "anime",
    "image": "/images/nooks-50/spirited-bathhouse.webp",
    "thumbnail": "/images/nooks-50/thumbs/spirited-bathhouse.webp",
    "theme": "botanical",
    "mood": "none",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Anime",
    "fandom": true
  },
  {
    "id": "bookshop-cat",
    "title": "Bookshop Cat",
    "caption": "A small independent bookshop after closing, lamps on and a cat at the counter",
    "category": "cozy",
    "style": "illustrated",
    "image": "/images/nooks-50/bookshop-cat.webp",
    "thumbnail": "/images/nooks-50/thumbs/bookshop-cat.webp",
    "theme": "botanical",
    "mood": "none",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cozy",
    "fandom": false
  },
  {
    "id": "sunlit-greenhouse",
    "title": "Greenhouse Study",
    "caption": "A glass conservatory desk surrounded by leaves, rain and warm terracotta",
    "category": "nature",
    "style": "watercolor",
    "image": "/images/nooks-50/sunlit-greenhouse.webp",
    "thumbnail": "/images/nooks-50/thumbs/sunlit-greenhouse.webp",
    "theme": "sky",
    "mood": "rain",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Nature",
    "fandom": false
  },
  {
    "id": "dragon-hatchery",
    "title": "Dragon Hatchery",
    "caption": "A quiet stone-and-timber study beside one warm dragon nest and a mountain window",
    "category": "elsewhere",
    "style": "illustrated",
    "image": "/images/nooks-50/dragon-hatchery.webp",
    "thumbnail": "/images/nooks-50/thumbs/dragon-hatchery.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Fantasy",
    "fandom": false
  },
  {
    "id": "velaris-study",
    "title": "ACOTAR — Velaris Study",
    "caption": "A moonlit riverside study, mountain silhouettes, starlit windows and jewel colors",
    "category": "elsewhere",
    "style": "cinematic",
    "image": "/images/nooks-50/velaris-study.webp",
    "thumbnail": "/images/nooks-50/thumbs/velaris-study.webp",
    "theme": "moonlight",
    "mood": "stars",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "BookTok",
    "fandom": true
  },
  {
    "id": "dragon-rider-study",
    "title": "Fourth Wing — Dragon Rider Study",
    "caption": "A stone academy study facing a mountain courtyard, with flight charts and a warm hearth",
    "category": "elsewhere",
    "style": "cinematic",
    "image": "/images/nooks-50/dragon-rider-study.webp",
    "thumbnail": "/images/nooks-50/thumbs/dragon-rider-study.webp",
    "theme": "botanical",
    "mood": "none",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "BookTok",
    "fandom": true
  },
  {
    "id": "hobbit-study",
    "title": "The Shire — Hobbit Study",
    "caption": "A round-door hillside study, abundant food, curved shelving and a green view",
    "category": "nature",
    "style": "illustrated",
    "image": "/images/nooks-50/hobbit-study.webp",
    "thumbnail": "/images/nooks-50/thumbs/hobbit-study.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Fantasy",
    "fandom": true
  },
  {
    "id": "animal-crossing-island",
    "title": "Animal Crossing — Island Study",
    "caption": "A soft toy-like island cottage, custom furniture and a museum corner",
    "category": "nature",
    "style": "illustrated",
    "image": "/images/nooks-50/animal-crossing-island.webp",
    "thumbnail": "/images/nooks-50/thumbs/animal-crossing-island.webp",
    "theme": "sky",
    "mood": "sea",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cozy games",
    "fandom": true
  },
  {
    "id": "cinnamoroll-cloud-cafe",
    "title": "Cinnamoroll — Cloud Café",
    "caption": "Cream-and-sky-blue café, fluffy cloud seats and tiny pastries",
    "category": "cozy",
    "style": "illustrated",
    "image": "/images/nooks-50/cinnamoroll-cloud-cafe.webp",
    "thumbnail": "/images/nooks-50/thumbs/cinnamoroll-cloud-cafe.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cute",
    "fandom": true
  },
  {
    "id": "witch-apothecary",
    "title": "Witch’s Apothecary",
    "caption": "A wooden desk between herb bundles, labeled glass bottles and a moonlit garden",
    "category": "elsewhere",
    "style": "illustrated",
    "image": "/images/nooks-50/witch-apothecary.webp",
    "thumbnail": "/images/nooks-50/thumbs/witch-apothecary.webp",
    "theme": "botanical",
    "mood": "none",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Fantasy",
    "fandom": false
  },
  {
    "id": "kyoto-teahouse",
    "title": "Kyoto Tea House",
    "caption": "A low desk beside shoji doors, a moss garden and gentle rain",
    "category": "nature",
    "style": "anime",
    "image": "/images/nooks-50/kyoto-teahouse.webp",
    "thumbnail": "/images/nooks-50/thumbs/kyoto-teahouse.webp",
    "theme": "sky",
    "mood": "rain",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Travel",
    "fandom": false
  },
  {
    "id": "oxford-library",
    "title": "Dark Academia — Candlelit College",
    "caption": "A stone college study with oak desks, old atlases and candlelight; no franchise symbols",
    "category": "cozy",
    "style": "cinematic",
    "image": "/images/nooks-50/oxford-library.webp",
    "thumbnail": "/images/nooks-50/thumbs/oxford-library.webp",
    "theme": "botanical",
    "mood": "none",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Academia",
    "fandom": false
  },
  {
    "id": "capybara-onsen",
    "title": "Capybara Onsen",
    "caption": "A sheltered study deck overlooking warm pools, stone, citrus and relaxed capybaras",
    "category": "nature",
    "style": "illustrated",
    "image": "/images/nooks-50/capybara-onsen.webp",
    "thumbnail": "/images/nooks-50/thumbs/capybara-onsen.webp",
    "theme": "lavender",
    "mood": "none",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cute",
    "fandom": false
  },
  {
    "id": "pokemon-research-cottage",
    "title": "Pokémon — Research Cottage",
    "caption": "A warm field-research desk with notebooks, terrariums and a grassy outdoor view",
    "category": "nature",
    "style": "anime",
    "image": "/images/nooks-50/pokemon-research-cottage.webp",
    "thumbnail": "/images/nooks-50/thumbs/pokemon-research-cottage.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cozy games",
    "fandom": true
  },
  {
    "id": "sakura-garden",
    "title": "Cherry Blossom Study",
    "caption": "An open window, drifting petals outside, cream stationery and a flowering courtyard",
    "category": "nature",
    "style": "watercolor",
    "image": "/images/nooks-50/sakura-garden.webp",
    "thumbnail": "/images/nooks-50/thumbs/sakura-garden.webp",
    "theme": "sunrise",
    "mood": "petals",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Nature",
    "fandom": false
  },
  {
    "id": "paris-attic",
    "title": "Paris Attic",
    "caption": "A small sloped-ceiling study above zinc roofs, with coffee and a balcony",
    "category": "city",
    "style": "watercolor",
    "image": "/images/nooks-50/paris-attic.webp",
    "thumbnail": "/images/nooks-50/thumbs/paris-attic.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Travel",
    "fandom": false
  },
  {
    "id": "underwater-study",
    "title": "Underwater Library",
    "caption": "A dry, warmly lit glass study inside a deep-blue ocean observatory",
    "category": "elsewhere",
    "style": "dreamlike",
    "image": "/images/nooks-50/underwater-study.webp",
    "thumbnail": "/images/nooks-50/thumbs/underwater-study.webp",
    "theme": "sky",
    "mood": "sea",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Dreamlike",
    "fandom": false
  },
  {
    "id": "moonlit-observatory",
    "title": "Moon Observatory",
    "caption": "A circular observatory, warm desk pool of light and a huge calm night sky",
    "category": "elsewhere",
    "style": "cinematic",
    "image": "/images/nooks-50/moonlit-observatory.webp",
    "thumbnail": "/images/nooks-50/thumbs/moonlit-observatory.webp",
    "theme": "moonlight",
    "mood": "stars",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Dreamlike",
    "fandom": false
  },
  {
    "id": "frog-pond-studio",
    "title": "Frog Pond Studio",
    "caption": "A tiny wooden studio at pond level, lily pads outside and practical watercolor tools",
    "category": "nature",
    "style": "watercolor",
    "image": "/images/nooks-50/frog-pond-studio.webp",
    "thumbnail": "/images/nooks-50/thumbs/frog-pond-studio.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cute",
    "fandom": false
  },
  {
    "id": "kuromi-midnight-desk",
    "title": "Kuromi — Midnight Desk",
    "caption": "Lilac-and-black desk, soft plush shapes and a mischievous but cozy night palette",
    "category": "cozy",
    "style": "dreamlike",
    "image": "/images/nooks-50/kuromi-midnight-desk.webp",
    "thumbnail": "/images/nooks-50/thumbs/kuromi-midnight-desk.webp",
    "theme": "moonlight",
    "mood": "stars",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cute",
    "fandom": true
  },
  {
    "id": "antique-workshop",
    "title": "Whisper of the Heart — Antique Workshop",
    "caption": "A wooden writing desk above an antique shop, violins, clocks and city hills",
    "category": "cozy",
    "style": "anime",
    "image": "/images/nooks-50/antique-workshop.webp",
    "thumbnail": "/images/nooks-50/thumbs/antique-workshop.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Anime",
    "fandom": true
  },
  {
    "id": "minecraft-cottage",
    "title": "Minecraft — Cottage Library",
    "caption": "A block-built cottage with lanterns, bookshelves, a farm patch and rain outside",
    "category": "cozy",
    "style": "pixel",
    "image": "/images/nooks-50/minecraft-cottage.webp",
    "thumbnail": "/images/nooks-50/thumbs/minecraft-cottage.webp",
    "theme": "sky",
    "mood": "rain",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cozy games",
    "fandom": true
  },
  {
    "id": "hateno-study",
    "title": "Zelda — Hateno Study",
    "caption": "A countryside research desk, weathered wood, blue ceramic details and green hills",
    "category": "nature",
    "style": "anime",
    "image": "/images/nooks-50/hateno-study.webp",
    "thumbnail": "/images/nooks-50/thumbs/hateno-study.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cozy games",
    "fandom": true
  },
  {
    "id": "sumeru-akademiya",
    "title": "Genshin Impact — Sumeru Akademiya",
    "caption": "A leafy scholarly terrace with geometric windows, manuscripts and hanging gardens",
    "category": "elsewhere",
    "style": "anime",
    "image": "/images/nooks-50/sumeru-akademiya.webp",
    "thumbnail": "/images/nooks-50/thumbs/sumeru-akademiya.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Anime",
    "fandom": true
  },
  {
    "id": "mage-archive",
    "title": "Frieren — Mage’s Archive",
    "caption": "An old inn study packed with spellbooks, meadow views and a gentle fantasy palette",
    "category": "elsewhere",
    "style": "anime",
    "image": "/images/nooks-50/mage-archive.webp",
    "thumbnail": "/images/nooks-50/thumbs/mage-archive.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Anime",
    "fandom": true
  },
  {
    "id": "cyberpunk-rain-loft",
    "title": "Cyberpunk Rain Loft",
    "caption": "A warm amber desk inside a dark loft, enormous wet neon city beyond",
    "category": "city",
    "style": "anime",
    "image": "/images/nooks-50/cyberpunk-rain-loft.webp",
    "thumbnail": "/images/nooks-50/thumbs/cyberpunk-rain-loft.webp",
    "theme": "botanical",
    "mood": "city",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "City",
    "fandom": false
  },
  {
    "id": "secret-door-study",
    "title": "Coraline — Secret Door Study",
    "caption": "A blue-walled attic desk with handmade objects and a mysterious little door",
    "category": "elsewhere",
    "style": "illustrated",
    "image": "/images/nooks-50/secret-door-study.webp",
    "thumbnail": "/images/nooks-50/thumbs/secret-door-study.webp",
    "theme": "botanical",
    "mood": "none",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Fantasy",
    "fandom": true
  },
  {
    "id": "nevermore-study",
    "title": "Wednesday — Nevermore Study",
    "caption": "A gothic school writing desk with stained glass, black ink and a quieter monochrome palette",
    "category": "cozy",
    "style": "cinematic",
    "image": "/images/nooks-50/nevermore-study.webp",
    "thumbnail": "/images/nooks-50/thumbs/nevermore-study.webp",
    "theme": "moonlight",
    "mood": "none",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Academia",
    "fandom": true
  },
  {
    "id": "autumn-bakery",
    "title": "Autumn Bakery",
    "caption": "A small café desk by a bakery window, orange leaves and warm bread light",
    "category": "cozy",
    "style": "illustrated",
    "image": "/images/nooks-50/autumn-bakery.webp",
    "thumbnail": "/images/nooks-50/thumbs/autumn-bakery.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cozy",
    "fandom": false
  },
  {
    "id": "seoul-night-cafe",
    "title": "Seoul Late-Night Café",
    "caption": "A clean cream-and-wood café desk, desserts, city rain and a little late-night neon",
    "category": "city",
    "style": "anime",
    "image": "/images/nooks-50/seoul-night-cafe.webp",
    "thumbnail": "/images/nooks-50/thumbs/seoul-night-cafe.webp",
    "theme": "sky",
    "mood": "rain",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "City",
    "fandom": false
  },
  {
    "id": "cloud-cafe",
    "title": "Cloud Café",
    "caption": "An original sky café with warm ivory clouds, peach light and a stable desk",
    "category": "elsewhere",
    "style": "dreamlike",
    "image": "/images/nooks-50/cloud-cafe.webp",
    "thumbnail": "/images/nooks-50/thumbs/cloud-cafe.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Dreamlike",
    "fandom": false
  },
  {
    "id": "tiny-mouse-house",
    "title": "Tiny Mouse House",
    "caption": "A miniature desk built into a bookshelf, with spool stools and a teacup bed",
    "category": "cozy",
    "style": "illustrated",
    "image": "/images/nooks-50/tiny-mouse-house.webp",
    "thumbnail": "/images/nooks-50/thumbs/tiny-mouse-house.webp",
    "theme": "lavender",
    "mood": "none",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Cute",
    "fandom": false
  },
  {
    "id": "woodland-treehouse",
    "title": "Fairy Treehouse",
    "caption": "A sheltered desk within an enormous tree, warm windows and a misty canopy",
    "category": "nature",
    "style": "illustrated",
    "image": "/images/nooks-50/woodland-treehouse.webp",
    "thumbnail": "/images/nooks-50/thumbs/woodland-treehouse.webp",
    "theme": "botanical",
    "mood": "none",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Nature",
    "fandom": false
  },
  {
    "id": "aurora-cabin",
    "title": "Northern Lights Cabin",
    "caption": "A compact warm cabin with a panoramic northern sky and deep snow",
    "category": "nature",
    "style": "cinematic",
    "image": "/images/nooks-50/aurora-cabin.webp",
    "thumbnail": "/images/nooks-50/thumbs/aurora-cabin.webp",
    "theme": "botanical",
    "mood": "snow",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Travel",
    "fandom": false
  },
  {
    "id": "lighthouse-study",
    "title": "Ocean Lighthouse",
    "caption": "A curved coastal study with books, a lantern and a wide sea horizon",
    "category": "elsewhere",
    "style": "watercolor",
    "image": "/images/nooks-50/lighthouse-study.webp",
    "thumbnail": "/images/nooks-50/thumbs/lighthouse-study.webp",
    "theme": "sky",
    "mood": "sea",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Travel",
    "fandom": false
  },
  {
    "id": "desert-casita",
    "title": "Desert Courtyard",
    "caption": "A shaded riad-like study with terracotta, geometric tile, plants and a still fountain",
    "category": "nature",
    "style": "illustrated",
    "image": "/images/nooks-50/desert-casita.webp",
    "thumbnail": "/images/nooks-50/thumbs/desert-casita.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Travel",
    "fandom": false
  },
  {
    "id": "stationery-studio",
    "title": "Vintage Stationery Studio",
    "caption": "A warm paper-focused desk with ink, stamps, envelopes and neatly kept tools",
    "category": "cozy",
    "style": "illustrated",
    "image": "/images/nooks-50/stationery-studio.webp",
    "thumbnail": "/images/nooks-50/thumbs/stationery-studio.webp",
    "theme": "sunrise",
    "mood": "sun",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Academia",
    "fandom": false
  },
  {
    "id": "thousand-sunny-study",
    "title": "One Piece — Thousand Sunny Study",
    "caption": "A sheltered shipboard writing desk, maps, warm timber and a calm sea",
    "category": "elsewhere",
    "style": "anime",
    "image": "/images/nooks-50/thousand-sunny-study.webp",
    "thumbnail": "/images/nooks-50/thumbs/thousand-sunny-study.webp",
    "theme": "sky",
    "mood": "sea",
    "width": 1672,
    "height": 941,
    "segments": [],
    "collection": "Anime",
    "fandom": true
  }
] as const satisfies readonly RoomScene[];
export type RoomId = (typeof roomScenes)[number]['id'] | (typeof legacyRoomScenes)[number]['id'];
export const allRoomScenes: readonly RoomScene[] = [...roomScenes, ...legacyRoomScenes.filter(scene => !roomScenes.some(current => current.id === scene.id))];
export const roomCategories: { id: RoomCategory | 'all'; title: string }[] = [{ id: 'all', title: 'All' }, { id: 'cozy', title: 'Cozy' }, { id: 'nature', title: 'Nature' }, { id: 'city', title: 'City' }, { id: 'elsewhere', title: 'Elsewhere' }];
function curatedRoom(id: RoomId): RoomScene { return allRoomScenes.find(room => room.id === id) ?? roomScenes[0]; }
export const ROOM_SCENES: Record<SpaceTheme, RoomScene> = {
  botanical: curatedRoom('rainy-library'),
  moonlight: curatedRoom('rainy-library'),
  sunrise: curatedRoom('sakura-garden'),
  lavender: curatedRoom('sakura-garden'),
  sky: curatedRoom('midnight-train'),
};
export function getRoomScene(space: WorkspaceSpace): RoomScene {
  const selected = allRoomScenes.find(room => room.id === space.room) ?? ROOM_SCENES[space.theme] ?? roomScenes[0];
  const custom = safeBackgroundImage(space.backgroundImage);
  return custom ? { ...selected, image: custom, title: 'Your own nook', caption: 'Your uploaded artwork', mood: 'none', segments: [] } : selected;
}
export function getRoomImage(space: WorkspaceSpace): string { return getRoomScene(space).image; }
export const themes: { id: SpaceTheme; name: string; caption: string; colors: string[]; image: string }[] = [
  { id: 'botanical', name: 'Rainy library', caption: 'Amber lamps & city rain', image: ROOM_SCENES.botanical.image, colors: ['#f2f5e8', '#b8d9a4', '#e5c798'] },
  { id: 'moonlight', name: 'After hours', caption: 'Library nook · dark palette', image: ROOM_SCENES.moonlight.image, colors: ['#202c28', '#456c53', '#c5d5ac'] },
  { id: 'sunrise', name: 'Sakura garden', caption: 'Petals & afternoon light', image: ROOM_SCENES.sunrise.image, colors: ['#fff2e7', '#efc59f', '#d89779'] },
  { id: 'lavender', name: 'Rose dusk', caption: 'Garden nook · rose palette', image: ROOM_SCENES.lavender.image, colors: ['#f2eef8', '#c7b9e0', '#a899c8'] },
  { id: 'sky', name: 'Midnight train', caption: 'Moonlit countryside', image: ROOM_SCENES.sky.image, colors: ['#edf5f7', '#b7d6e2', '#91b6c6'] },
];
export const accents = [{ value: '#8bc8a7', name: 'Sage' }, { value: '#e9ab86', name: 'Peach' }, { value: '#b1a0d8', name: 'Lavender' }, { value: '#8cbad1', name: 'Sky' }, { value: '#d7a0b1', name: 'Rose' }];
const palettes: Record<SpaceTheme, { bg: string; surface: string; ink: string; muted: string; line: string }> = {
  botanical: { bg: '#f4f6ed', surface: '#fffef8', ink: '#283d32', muted: '#7a887d', line: '#e0e6d9' },
  moonlight: { bg: '#202d29', surface: '#2b3b34', ink: '#ebf2e6', muted: '#a5b5a7', line: '#425247' },
  sunrise: { bg: '#fff4e9', surface: '#fffcf7', ink: '#594438', muted: '#9e8978', line: '#efdfcf' },
  lavender: { bg: '#f4f0f9', surface: '#fffdff', ink: '#4b425a', muted: '#948b9e', line: '#e5dfef' },
  sky: { bg: '#eef5f7', surface: '#fcfeff', ink: '#334b54', muted: '#80959d', line: '#dce9ed' },
};
export function getSpaceStyle(space: WorkspaceSpace): CSSProperties {
  const palette = palettes[space.theme] ?? palettes.botanical;
  const accentStyles: Record<string, { ink: string; light: string; darkLight: string }> = {
    '#8bc8a7': { ink: '#33734d', light: '#e2f2e7', darkLight: '#314b3c' },
    '#e9ab86': { ink: '#97502d', light: '#fbe7d9', darkLight: '#514134' },
    '#b1a0d8': { ink: '#745297', light: '#eee7f8', darkLight: '#443c51' },
    '#8cbad1': { ink: '#356b85', light: '#e1eff6', darkLight: '#354951' },
    '#d7a0b1': { ink: '#924f66', light: '#f6e5ed', darkLight: '#4e3943' },
  };
  const selected = accentStyles[space.accent] ?? accentStyles[defaultSpace.accent];
  const dark = space.theme === 'moonlight';
  return { '--space-bg': palette.bg, '--space-surface': palette.surface, '--space-ink': palette.ink, '--space-muted': palette.muted, '--space-line': palette.line, '--space-accent': space.accent, '--bg': palette.bg, '--surface': palette.surface, '--ink': palette.ink, '--muted': palette.muted, '--line': palette.line, '--accent': dark ? space.accent : selected.ink, '--accent-light': dark ? selected.darkLight : selected.light, '--sidebar': dark ? '#26352d' : palette.surface, '--accent-foreground': dark ? '#23312a' : '#ffffff', colorScheme: dark ? 'dark' : 'light' } as CSSProperties;
}
export function safeBackgroundImage(image?: string): string | undefined {
  return image && image.length <= 1_000_000 && /^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(image) ? image : undefined;
}
